// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBusinessesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "businesses",
		Short:       "Get and update businesses",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBusinessesGetBusinessCmd(flags))
	cmd.AddCommand(newBusinessesUpdateBusinessCmd(flags))
	cmd.AddCommand(newBusinessesAdAccountsCmd(flags))
	cmd.AddCommand(newBusinessesFundingInstrumentsCmd(flags))
	cmd.AddCommand(newBusinessesPixelsCmd(flags))
	cmd.AddCommand(newBusinessesProductCatalogsCmd(flags))
	cmd.AddCommand(newBusinessesProfilesCmd(flags))
	return cmd
}
