// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFundingInstrumentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "funding-instruments",
		Short:       "View funding instrument details",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFundingInstrumentsAllocationsCmd(flags))
	return cmd
}
