// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMeListMyBusinessesCmd(flags *rootFlags) *cobra.Command {
	var flagAdAccountId string
	var flagRole string
	var flagPageToken string
	var flagPageSize int

	cmd := &cobra.Command{
		Use:         "list-my-businesses",
		Short:       "List businesses linked to your account",
		Example:     "  reddit-ads-pp-cli me list-my-businesses",
		Annotations: map[string]string{"pp:endpoint": "me.list-my-businesses", "pp:method": "GET", "pp:path": "/me/businesses", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("role") {
				allowedRole := []string{"BUSINESS_ADMIN", "CATALOG_ADMIN"}
				validRole := false
				for _, v := range allowedRole {
					if flagRole == v {
						validRole = true
						break
					}
				}
				if !validRole {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagRole, "role", allowedRole)
				}
			}
			path := "/me/businesses"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagAdAccountId != "" {
				params["ad_account_id"] = formatCLIParamValue(flagAdAccountId)
			}
			if flagRole != "" {
				params["role"] = formatCLIParamValue(flagRole)
			}
			if flagPageToken != "" {
				params["page.token"] = formatCLIParamValue(flagPageToken)
			}
			if flagPageSize != 0 {
				params["page.size"] = formatCLIParamValue(flagPageSize)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "me", false, path, params, nil, "data", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagAdAccountId, "ad-account-id", "", "Filter by the ID of the ad account the user has access to.")
	cmd.Flags().StringVar(&flagRole, "role", "", "Filter by the business role the user has. (one of: BUSINESS_ADMIN, CATALOG_ADMIN)")
	cmd.Flags().StringVar(&flagPageToken, "page-token", "", "The token for the page to retrieve.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "The number of items to be returned by page.")

	return cmd
}
