// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newProductSetsProductsListInSetCmd(flags *rootFlags) *cobra.Command {
	var flagIds string
	var flagApprovalDecision string
	var flagSearch string
	var flagIssueCode string
	var flagPageToken string
	var flagPageSize int

	cmd := &cobra.Command{
		Use:         "list-in-set <product_set_id>",
		Aliases:     []string{"get"},
		Short:       "List products in a product set",
		Example:     "  reddit-ads-pp-cli product-sets products list-in-set 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "products.list-in-set", "pp:method": "GET", "pp:path": "/product_sets/{product_set_id}/products", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <product_set_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <product_set_id>"))
			}
			if cmd.Flags().Changed("approval-decision") {
				allowedApprovalDecision := []string{"PENDING", "APPROVED", "REJECTED"}
				validApprovalDecision := false
				for _, v := range allowedApprovalDecision {
					if flagApprovalDecision == v {
						validApprovalDecision = true
						break
					}
				}
				if !validApprovalDecision {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagApprovalDecision, "approval-decision", allowedApprovalDecision)
				}
			}
			if cmd.Flags().Changed("issue-code") {
				allowedIssueCode := []string{"INVALID_ADDITIONAL_IMAGE_LINKS", "INVALID_SALE_PRICE", "INVALID_SALE_PRICE_EFFECTIVE_DATE", "INVALID_EXPIRATION_DATE", "IMAGE_PROCESSING_ERROR", "IMAGE_REJECTED", "LOW_IMAGE_QUALITY", "INVALID_CUSTOM_LABEL_0", "INVALID_CUSTOM_LABEL_1", "INVALID_CUSTOM_LABEL_2", "INVALID_CUSTOM_LABEL_3", "INVALID_CUSTOM_LABEL_4", "INVALID_GOOGLE_PRODUCT_CATEGORY", "INVALID_PRODUCT_TYPE", "INVALID_BRAND", "INVALID_GTIN", "INVALID_MPN", "INVALID_ITEM_GROUP_ID", "INVALID_COST_OF_GOODS_SOLD", "INVALID_AVAILABILITY", "INVALID_MOBILE_LINK", "INVALID_PLATFORM_SPECIFIC_LINK", "INVALID_AVERAGE_REVIEW_RATING", "INVALID_NUMBER_OF_RATINGS", "INVALID_CONDITION", "INVALID_AGE_GROUP", "INVALID_GENDER", "INVALID_COLOR", "INVALID_SIZE", "INVALID_SIZE_TYPE", "INVALID_MATERIAL", "INVALID_PATTERN", "INVALID_CUSTOM_NUMBER_0", "INVALID_CUSTOM_NUMBER_1", "INVALID_CUSTOM_NUMBER_2", "INVALID_CUSTOM_NUMBER_3", "INVALID_CUSTOM_NUMBER_4", "INVALID_PRODUCT_DETAIL", "INVALID_PRODUCT_HIGHLIGHT", "INVALID_LIFESTYLE_IMAGE_LINK", "INVALID_IS_BUNDLE", "INCOMPATIBLE_WITH_FUTURE_RELEASE"}
				validIssueCode := false
				for _, v := range allowedIssueCode {
					if flagIssueCode == v {
						validIssueCode = true
						break
					}
				}
				if !validIssueCode {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagIssueCode, "issue-code", allowedIssueCode)
				}
			}
			path := "/product_sets/{product_set_id}/products"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("product_set_id is required\nUsage: %s <%s>", cmd.CommandPath(), "product_set_id"))
			}
			path = replacePathParam(path, "product_set_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if flagIds != "" {
				path = appendArrayQueryParam(path, "ids", flagIds, "form", true)
			}
			params := map[string]string{}
			if flagApprovalDecision != "" {
				params["approval_decision"] = formatCLIParamValue(flagApprovalDecision)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagIssueCode != "" {
				params["issue_code"] = formatCLIParamValue(flagIssueCode)
			}
			if flagPageToken != "" {
				params["page.token"] = formatCLIParamValue(flagPageToken)
			}
			if flagPageSize != 0 {
				params["page.size"] = formatCLIParamValue(flagPageSize)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "products", false, path, params, nil, "data", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagIds, "ids", "", "Filter by product IDs.")
	cmd.Flags().StringVar(&flagApprovalDecision, "approval-decision", "", "Filter by an approval decision. (one of: PENDING, APPROVED, REJECTED)")
	cmd.Flags().StringVar(&flagSearch, "search", "", "Filter by a term.")
	cmd.Flags().StringVar(&flagIssueCode, "issue-code", "", "Filter by an issue code. (one of: INVALID_ADDITIONAL_IMAGE_LINKS, INVALID_SALE_PRICE, INVALID_SALE_PRICE_EFFECTIVE_DATE, INVALID_EXPIRATION_DATE, IMAGE_PROCESSING_ERROR, IMAGE_REJECTED, LOW_IMAGE_QUALITY, INVALID_CUSTOM_LABEL_0, INVALID_CUSTOM_LABEL_1, INVALID_CUSTOM_LABEL_2, INVALID_CUSTOM_LABEL_3, INVALID_CUSTOM_LABEL_4, INVALID_GOOGLE_PRODUCT_CATEGORY, INVALID_PRODUCT_TYPE, INVALID_BRAND, INVALID_GTIN, INVALID_MPN, INVALID_ITEM_GROUP_ID, INVALID_COST_OF_GOODS_SOLD, INVALID_AVAILABILITY, INVALID_MOBILE_LINK, INVALID_PLATFORM_SPECIFIC_LINK, INVALID_AVERAGE_REVIEW_RATING, INVALID_NUMBER_OF_RATINGS, INVALID_CONDITION, INVALID_AGE_GROUP, INVALID_GENDER, INVALID_COLOR, INVALID_SIZE, INVALID_SIZE_TYPE, INVALID_MATERIAL, INVALID_PATTERN, INVALID_CUSTOM_NUMBER_0, INVALID_CUSTOM_NUMBER_1, INVALID_CUSTOM_NUMBER_2, INVALID_CUSTOM_NUMBER_3, INVALID_CUSTOM_NUMBER_4, INVALID_PRODUCT_DETAIL, INVALID_PRODUCT_HIGHLIGHT, INVALID_LIFESTYLE_IMAGE_LINK, INVALID_IS_BUNDLE, INCOMPATIBLE_WITH_FUTURE_RELEASE)")
	cmd.Flags().StringVar(&flagPageToken, "page-token", "", "The token for the page to retrieve.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "The number of items to be returned by page.")

	return cmd
}
