// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"reddit-ads-pp-cli/internal/cliutil"
)

func newForecastingPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDataAdAccountId string
	var bodyDataAttributionType string
	var bodyDataBidStrategy string
	var bodyDataBidType string
	var bodyDataCampaignObjective string
	var bodyDataCurrency string
	var bodyDataDurationEndTime string
	var bodyDataDurationStartTime string
	var bodyDataEndTime string
	var bodyDataGoalType string
	var bodyDataGoalValue int
	var bodyDataIsCampaignBudgetOptimization bool
	var bodyDataOptimizationGoal string
	var bodyDataStartTime string
	var bodyDataTargetingCarriers string
	var bodyDataTargetingCommunities string
	var bodyDataTargetingCustomAudienceIds string
	var bodyDataTargetingDevices string
	var bodyDataTargetingExcludedCommunities string
	var bodyDataTargetingExcludedCustomAudienceIds string
	var bodyDataTargetingExcludedGeolocations string
	var bodyDataTargetingExcludedInterests string
	var bodyDataTargetingExcludedKeywords string
	var bodyDataTargetingExpandTargeting bool
	var bodyDataTargetingGender string
	var bodyDataTargetingGeolocations string
	var bodyDataTargetingInterests string
	var bodyDataTargetingKeywords string
	var bodyDataTargetingLanguages string
	var bodyDataTargetingLocations string
	var bodyDataTargetingPlatforms string
	var bodyDataTargetingSuppressionEventTypes string
	var bodyDataTargetingViewModes string
	var bodyDataViewThroughConversionType string

	cmd := &cobra.Command{
		Use:         "forecasting",
		Short:       "Get bid suggestions based on recent auctions",
		Long:        "Retrieve bid suggestions based on recent auction outcomes for a given set of targeting, budget, and bidding parameters.",
		Example:     `# Forecast reach and spend for a planned campaign before submitting the budget request
cat forecast-request.json | reddit-ads forecasting --data-ad-account-id a2_9f8e7d --stdin

# Inline forecast for a simple awareness campaign with basic geo targeting
reddit-ads forecasting --data-ad-account-id a2_9f8e7d --data-campaign-objective BRAND_AWARENESS --data-bid-type CPM --data-targeting-geolocations US --data-start-time 2026-08-01T00:00:00Z --data-end-time 2026-08-31T00:00:00Z`,
		Annotations: map[string]string{"pp:endpoint": "forecasting.generate-bid-suggestion", "pp:method": "POST", "pp:path": "/forecasting/bid_suggestions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("data-duration-start-time") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-duration-start-time")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/forecasting/bid_suggestions"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			{
				nestedData := map[string]any{}
				if bodyDataAdAccountId != "" {
					nestedData["ad_account_id"] = bodyDataAdAccountId
				}
				if bodyDataAttributionType != "" {
					nestedData["attribution_type"] = bodyDataAttributionType
				}
				if bodyDataBidStrategy != "" {
					nestedData["bid_strategy"] = bodyDataBidStrategy
				}
				if bodyDataBidType != "" {
					nestedData["bid_type"] = bodyDataBidType
				}
				if bodyDataCampaignObjective != "" {
					nestedData["campaign_objective"] = bodyDataCampaignObjective
				}
				if bodyDataCurrency != "" {
					nestedData["currency"] = bodyDataCurrency
				}
				{
					nestedDataDuration := map[string]any{}
					if bodyDataDurationEndTime != "" {
						nestedDataDuration["end_time"] = bodyDataDurationEndTime
					}
					if bodyDataDurationStartTime != "" {
						nestedDataDuration["start_time"] = bodyDataDurationStartTime
					}
					if len(nestedDataDuration) > 0 {
						nestedData["duration"] = nestedDataDuration
					}
				}
				if bodyDataEndTime != "" {
					nestedData["end_time"] = bodyDataEndTime
				}
				if bodyDataGoalType != "" {
					nestedData["goal_type"] = bodyDataGoalType
				}
				if bodyDataGoalValue != 0 {
					nestedData["goal_value"] = bodyDataGoalValue
				}
				if cmd.Flags().Changed("data-is-campaign-budget-optimization") {
					nestedData["is_campaign_budget_optimization"] = bodyDataIsCampaignBudgetOptimization
				}
				if bodyDataOptimizationGoal != "" {
					nestedData["optimization_goal"] = bodyDataOptimizationGoal
				}
				if bodyDataStartTime != "" {
					nestedData["start_time"] = bodyDataStartTime
				}
				{
					nestedDataTargeting := map[string]any{}
					if cmd.Flags().Changed("data-targeting-carriers") {
						parsedDataTargetingCarriers, parseErr := cliutil.ParseStringList(bodyDataTargetingCarriers)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-carriers list: %w", parseErr)
						}
						nestedDataTargeting["carriers"] = parsedDataTargetingCarriers
					}
					if cmd.Flags().Changed("data-targeting-communities") {
						parsedDataTargetingCommunities, parseErr := cliutil.ParseStringList(bodyDataTargetingCommunities)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-communities list: %w", parseErr)
						}
						nestedDataTargeting["communities"] = parsedDataTargetingCommunities
					}
					if cmd.Flags().Changed("data-targeting-custom-audience-ids") {
						parsedDataTargetingCustomAudienceIds, parseErr := cliutil.ParseStringList(bodyDataTargetingCustomAudienceIds)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-custom-audience-ids list: %w", parseErr)
						}
						nestedDataTargeting["custom_audience_ids"] = parsedDataTargetingCustomAudienceIds
					}
					if bodyDataTargetingDevices != "" {
						var parsedDataTargetingDevices any
						if err := json.Unmarshal([]byte(bodyDataTargetingDevices), &parsedDataTargetingDevices); err != nil {
							return fmt.Errorf("parsing --data-targeting-devices JSON: %w", err)
						}
						asArray, ok := parsedDataTargetingDevices.([]any)
						if !ok {
							return fmt.Errorf("--data-targeting-devices must be a JSON array, got JSON %T", parsedDataTargetingDevices)
						}
						nestedDataTargeting["devices"] = asArray
					}
					if cmd.Flags().Changed("data-targeting-excluded-communities") {
						parsedDataTargetingExcludedCommunities, parseErr := cliutil.ParseStringList(bodyDataTargetingExcludedCommunities)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-excluded-communities list: %w", parseErr)
						}
						nestedDataTargeting["excluded_communities"] = parsedDataTargetingExcludedCommunities
					}
					if cmd.Flags().Changed("data-targeting-excluded-custom-audience-ids") {
						parsedDataTargetingExcludedCustomAudienceIds, parseErr := cliutil.ParseStringList(bodyDataTargetingExcludedCustomAudienceIds)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-excluded-custom-audience-ids list: %w", parseErr)
						}
						nestedDataTargeting["excluded_custom_audience_ids"] = parsedDataTargetingExcludedCustomAudienceIds
					}
					if cmd.Flags().Changed("data-targeting-excluded-geolocations") {
						parsedDataTargetingExcludedGeolocations, parseErr := cliutil.ParseStringList(bodyDataTargetingExcludedGeolocations)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-excluded-geolocations list: %w", parseErr)
						}
						nestedDataTargeting["excluded_geolocations"] = parsedDataTargetingExcludedGeolocations
					}
					if cmd.Flags().Changed("data-targeting-excluded-interests") {
						parsedDataTargetingExcludedInterests, parseErr := cliutil.ParseStringList(bodyDataTargetingExcludedInterests)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-excluded-interests list: %w", parseErr)
						}
						nestedDataTargeting["excluded_interests"] = parsedDataTargetingExcludedInterests
					}
					if cmd.Flags().Changed("data-targeting-excluded-keywords") {
						parsedDataTargetingExcludedKeywords, parseErr := cliutil.ParseStringList(bodyDataTargetingExcludedKeywords)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-excluded-keywords list: %w", parseErr)
						}
						nestedDataTargeting["excluded_keywords"] = parsedDataTargetingExcludedKeywords
					}
					if cmd.Flags().Changed("data-targeting-expand-targeting") {
						nestedDataTargeting["expand_targeting"] = bodyDataTargetingExpandTargeting
					}
					if bodyDataTargetingGender != "" {
						nestedDataTargeting["gender"] = bodyDataTargetingGender
					}
					if cmd.Flags().Changed("data-targeting-geolocations") {
						parsedDataTargetingGeolocations, parseErr := cliutil.ParseStringList(bodyDataTargetingGeolocations)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-geolocations list: %w", parseErr)
						}
						nestedDataTargeting["geolocations"] = parsedDataTargetingGeolocations
					}
					if cmd.Flags().Changed("data-targeting-interests") {
						parsedDataTargetingInterests, parseErr := cliutil.ParseStringList(bodyDataTargetingInterests)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-interests list: %w", parseErr)
						}
						nestedDataTargeting["interests"] = parsedDataTargetingInterests
					}
					if cmd.Flags().Changed("data-targeting-keywords") {
						parsedDataTargetingKeywords, parseErr := cliutil.ParseStringList(bodyDataTargetingKeywords)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-keywords list: %w", parseErr)
						}
						nestedDataTargeting["keywords"] = parsedDataTargetingKeywords
					}
					if cmd.Flags().Changed("data-targeting-languages") {
						parsedDataTargetingLanguages, parseErr := cliutil.ParseStringList(bodyDataTargetingLanguages)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-languages list: %w", parseErr)
						}
						nestedDataTargeting["languages"] = parsedDataTargetingLanguages
					}
					if cmd.Flags().Changed("data-targeting-locations") {
						parsedDataTargetingLocations, parseErr := cliutil.ParseStringList(bodyDataTargetingLocations)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-locations list: %w", parseErr)
						}
						nestedDataTargeting["locations"] = parsedDataTargetingLocations
					}
					if cmd.Flags().Changed("data-targeting-platforms") {
						parsedDataTargetingPlatforms, parseErr := cliutil.ParseStringList(bodyDataTargetingPlatforms)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-platforms list: %w", parseErr)
						}
						nestedDataTargeting["platforms"] = parsedDataTargetingPlatforms
					}
					if cmd.Flags().Changed("data-targeting-suppression-event-types") {
						parsedDataTargetingSuppressionEventTypes, parseErr := cliutil.ParseStringList(bodyDataTargetingSuppressionEventTypes)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-suppression-event-types list: %w", parseErr)
						}
						nestedDataTargeting["suppression_event_types"] = parsedDataTargetingSuppressionEventTypes
					}
					if cmd.Flags().Changed("data-targeting-view-modes") {
						parsedDataTargetingViewModes, parseErr := cliutil.ParseStringList(bodyDataTargetingViewModes)
						if parseErr != nil {
							return fmt.Errorf("parsing --data-targeting-view-modes list: %w", parseErr)
						}
						nestedDataTargeting["view_modes"] = parsedDataTargetingViewModes
					}
					if len(nestedDataTargeting) > 0 {
						nestedData["targeting"] = nestedDataTargeting
					}
				}
				if bodyDataViewThroughConversionType != "" {
					nestedData["view_through_conversion_type"] = bodyDataViewThroughConversionType
				}
				if len(nestedData) > 0 {
					bodyMap["data"] = nestedData
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "forecasting", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&bodyDataAdAccountId, "data-ad-account-id", "", "The ad account ID.")
	cmd.Flags().StringVar(&bodyDataAttributionType, "data-attribution-type", "", "DEPRECATED: This field is no longer used. It will be ignored if provided.")
	cmd.Flags().StringVar(&bodyDataBidStrategy, "data-bid-strategy", "", "The ad group's bid strategy. For CBO campaigns, this must match the campaign's bid strategy.")
	cmd.Flags().StringVar(&bodyDataBidType, "data-bid-type", "", "The bid type.")
	cmd.Flags().StringVar(&bodyDataCampaignObjective, "data-campaign-objective", "", "The [campaign objective](https://business.reddithelp.com/s/article/Ad-campaign-objectives).")
	cmd.Flags().StringVar(&bodyDataCurrency, "data-currency", "", "The currency symbol used ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).")
	cmd.Flags().StringVar(&bodyDataDurationEndTime, "data-duration-end-time", "", "The end time ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).")
	cmd.Flags().StringVar(&bodyDataDurationStartTime, "data-duration-start-time", "", "The start time ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).")
	cmd.Flags().StringVar(&bodyDataEndTime, "data-end-time", "", "DEPRECATED: This field is no longer used. It will be ignored if provided. Use `data.duration.end_time` instead.")
	cmd.Flags().StringVar(&bodyDataGoalType, "data-goal-type", "", "The goal objective of the ad group.")
	cmd.Flags().IntVar(&bodyDataGoalValue, "data-goal-value", 0, "The goal value (microcurrency).")
	cmd.Flags().BoolVar(&bodyDataIsCampaignBudgetOptimization, "data-is-campaign-budget-optimization", false, "Whether the ad group belongs to a CBO (campaign budget optimization) campaign. This cannot be modified with the API.")
	cmd.Flags().StringVar(&bodyDataOptimizationGoal, "data-optimization-goal", "", "The event you want to measure. Must match the campaign's optimization goal for CBO campaigns.")
	cmd.Flags().StringVar(&bodyDataStartTime, "data-start-time", "", "DEPRECATED: This field is no longer used. It will be ignored if provided. Use `data.duration.start_time` instead.")
	cmd.Flags().StringVar(&bodyDataTargetingCarriers, "data-targeting-carriers", "", "The [mobile carriers](https://ads-api.reddit.com/docs/v3/operations/List%20Carriers) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingCommunities, "data-targeting-communities", "", "The [Reddit communities ('subreddits')](https://ads-api.reddit.com/docs/v3/operations/List%20Communities) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingCustomAudienceIds, "data-targeting-custom-audience-ids", "", "The [custom audiences](https://ads-api.reddit.com/docs/v3/operations/List%20User%20Custom%20Audiences) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingDevices, "data-targeting-devices", "", "The [devices](https://ads-api.reddit.com/docs/v3/operations/List%20Devices) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingExcludedCommunities, "data-targeting-excluded-communities", "", "The communities ('subreddits') to exclude from targeting. Ads won't be eligible for auctions in these communities.")
	cmd.Flags().StringVar(&bodyDataTargetingExcludedCustomAudienceIds, "data-targeting-excluded-custom-audience-ids", "", "The custom audiences to exclude from targeting.")
	cmd.Flags().StringVar(&bodyDataTargetingExcludedGeolocations, "data-targeting-excluded-geolocations", "", "The geolocations to exclude from targeting.")
	cmd.Flags().StringVar(&bodyDataTargetingExcludedInterests, "data-targeting-excluded-interests", "", "The interests to exclude from targeting.")
	cmd.Flags().StringVar(&bodyDataTargetingExcludedKeywords, "data-targeting-excluded-keywords", "", "The keywords to exclude from targeting.")
	cmd.Flags().BoolVar(&bodyDataTargetingExpandTargeting, "data-targeting-expand-targeting", false, "Allow Reddit to expand your targeting options. Learn about [automated targeting](https://business.reddithelp.")
	cmd.Flags().StringVar(&bodyDataTargetingGender, "data-targeting-gender", "", "The gender group to target.")
	cmd.Flags().StringVar(&bodyDataTargetingGeolocations, "data-targeting-geolocations", "", "The [geolocations](https://ads-api.reddit.com/docs/v3/operations/List%20Geolocations) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingInterests, "data-targeting-interests", "", "The [interests](https://ads-api.reddit.com/docs/v3/operations/List%20Interests) to target.")
	cmd.Flags().StringVar(&bodyDataTargetingKeywords, "data-targeting-keywords", "", "The keywords to target.")
	cmd.Flags().StringVar(&bodyDataTargetingLanguages, "data-targeting-languages", "", "The [languages](https://ads-api.reddit.com/docs/v3/operations/List%20Languages) to target ([ISO 639-1](https://www.loc.")
	cmd.Flags().StringVar(&bodyDataTargetingLocations, "data-targeting-locations", "", "The client location to place the advertisement. For collections ads, only `FEED` is supported.")
	cmd.Flags().StringVar(&bodyDataTargetingPlatforms, "data-targeting-platforms", "", "The platforms to show the advertisement on. `DESKTOP_LEGACY` (legacy desktop) is deprecated and no longer supported.")
	cmd.Flags().StringVar(&bodyDataTargetingSuppressionEventTypes, "data-targeting-suppression-event-types", "", "The suppression event types.")
	cmd.Flags().StringVar(&bodyDataTargetingViewModes, "data-targeting-view-modes", "", "The layouts the ad can be placed in.")
	cmd.Flags().StringVar(&bodyDataViewThroughConversionType, "data-view-through-conversion-type", "", "The type of view-through conversion being measured.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
