// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTargetingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "targeting",
		Short:       "List, search, and validate targeting options",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTargetingDoGeolocationValidationsCmd(flags))
	cmd.AddCommand(newTargetingDoKeywordValidationsCmd(flags))
	cmd.AddCommand(newTargetingList3rdPartyAudiencesCmd(flags))
	cmd.AddCommand(newTargetingListCarriersCmd(flags))
	cmd.AddCommand(newTargetingListCommunitiesCmd(flags))
	cmd.AddCommand(newTargetingListCommunitiesSuggestionsCmd(flags))
	cmd.AddCommand(newTargetingListDevicesCmd(flags))
	cmd.AddCommand(newTargetingListGeolocationsCmd(flags))
	cmd.AddCommand(newTargetingListInterestsCmd(flags))
	cmd.AddCommand(newTargetingListKeywordSuggestionsCmd(flags))
	cmd.AddCommand(newTargetingListLanguagesCmd(flags))
	cmd.AddCommand(newTargetingSearchCommunitiesCmd(flags))
	return cmd
}
