// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newAccountsPartialUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyCreatedAt string
	var bodyCreatedBy int
	var bodyExternalId string
	var bodyId2 string
	var bodyName string
	var bodyNotebooks string
	var bodyPropertiesBillingId string
	var bodyPropertiesEmailDomains string
	var bodyPropertiesHubspotDealId string
	var bodyPropertiesKnownEmails string
	var bodyPropertiesMetabaseLink string
	var bodyPropertiesSfdcId string
	var bodyPropertiesSlackChannelId string
	var bodyPropertiesStripeCustomerId string
	var bodyPropertiesUsageDashboardLink string
	var bodyPropertiesZendeskId string
	var bodySlackSummaryCadence string
	var bodyTags string
	var bodyUpdatedAt string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "partial-update <project_id> <id>",
		Short:       "Partial update",
		Example:     "  posthog-pp-cli accounts partial-update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "accounts.partial-update", "pp:method": "PATCH", "pp:path": "/api/projects/{project_id}/accounts/{id}/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <id>"))
			}
			if !stdinBody {
			}
			path := "/api/projects/{project_id}/accounts/{id}/"
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				if bodyCreatedBy != 0 {
					bodyMap["created_by"] = bodyCreatedBy
				}
				if bodyExternalId != "" {
					bodyMap["external_id"] = bodyExternalId
				}
				if bodyId2 != "" {
					bodyMap["id"] = bodyId2
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if cmd.Flags().Changed("notebooks") {
					parsedNotebooks, parseErr := cliutil.ParseStringList(bodyNotebooks)
					if parseErr != nil {
						return fmt.Errorf("parsing --notebooks list: %w", parseErr)
					}
					bodyMap["notebooks"] = parsedNotebooks
				}
				{
					nestedProperties := map[string]any{}
					if bodyPropertiesBillingId != "" {
						nestedProperties["billing_id"] = bodyPropertiesBillingId
					}
					if cmd.Flags().Changed("properties-email-domains") {
						parsedPropertiesEmailDomains, parseErr := cliutil.ParseStringList(bodyPropertiesEmailDomains)
						if parseErr != nil {
							return fmt.Errorf("parsing --properties-email-domains list: %w", parseErr)
						}
						nestedProperties["email_domains"] = parsedPropertiesEmailDomains
					}
					if bodyPropertiesHubspotDealId != "" {
						nestedProperties["hubspot_deal_id"] = bodyPropertiesHubspotDealId
					}
					if cmd.Flags().Changed("properties-known-emails") {
						parsedPropertiesKnownEmails, parseErr := cliutil.ParseStringList(bodyPropertiesKnownEmails)
						if parseErr != nil {
							return fmt.Errorf("parsing --properties-known-emails list: %w", parseErr)
						}
						nestedProperties["known_emails"] = parsedPropertiesKnownEmails
					}
					if bodyPropertiesMetabaseLink != "" {
						nestedProperties["metabase_link"] = bodyPropertiesMetabaseLink
					}
					if bodyPropertiesSfdcId != "" {
						nestedProperties["sfdc_id"] = bodyPropertiesSfdcId
					}
					if bodyPropertiesSlackChannelId != "" {
						nestedProperties["slack_channel_id"] = bodyPropertiesSlackChannelId
					}
					if bodyPropertiesStripeCustomerId != "" {
						nestedProperties["stripe_customer_id"] = bodyPropertiesStripeCustomerId
					}
					if bodyPropertiesUsageDashboardLink != "" {
						nestedProperties["usage_dashboard_link"] = bodyPropertiesUsageDashboardLink
					}
					if bodyPropertiesZendeskId != "" {
						nestedProperties["zendesk_id"] = bodyPropertiesZendeskId
					}
					if len(nestedProperties) > 0 {
						bodyMap["properties"] = nestedProperties
					}
				}
				if bodySlackSummaryCadence != "" {
					bodyMap["slack_summary_cadence"] = bodySlackSummaryCadence
				}
				if cmd.Flags().Changed("tags") {
					parsedTags, parseErr := cliutil.ParseStringList(bodyTags)
					if parseErr != nil {
						return fmt.Errorf("parsing --tags list: %w", parseErr)
					}
					bodyMap["tags"] = parsedTags
				}
				if bodyUpdatedAt != "" {
					bodyMap["updated_at"] = bodyUpdatedAt
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "accounts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "accounts", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "accounts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().IntVar(&bodyCreatedBy, "created-by", 0, "Created by")
	cmd.Flags().StringVar(&bodyExternalId, "external-id", "", "Identifier linking this account to its source customer — the analytics group key (the customer's organization id)")
	cmd.Flags().StringVar(&bodyId2, "id-2", "", "Id")
	cmd.Flags().StringVar(&bodyName, "name", "", "Human-readable name of the account.")
	cmd.Flags().StringVar(&bodyNotebooks, "notebooks", "", "Short IDs of the internal notebooks linked to this account, used to persist investigations, call notes")
	cmd.Flags().StringVar(&bodyPropertiesBillingId, "properties-billing-id", "", "Billing id")
	cmd.Flags().StringVar(&bodyPropertiesEmailDomains, "properties-email-domains", "", "Email domains owned by this account's company, used to match inbound touchpoints to the account.")
	cmd.Flags().StringVar(&bodyPropertiesHubspotDealId, "properties-hubspot-deal-id", "", "Hubspot deal id")
	cmd.Flags().StringVar(&bodyPropertiesKnownEmails, "properties-known-emails", "", "Individual email addresses pinned to this account, matched before the domain fallback.")
	cmd.Flags().StringVar(&bodyPropertiesMetabaseLink, "properties-metabase-link", "", "Metabase link")
	cmd.Flags().StringVar(&bodyPropertiesSfdcId, "properties-sfdc-id", "", "Sfdc id")
	cmd.Flags().StringVar(&bodyPropertiesSlackChannelId, "properties-slack-channel-id", "", "Slack channel id")
	cmd.Flags().StringVar(&bodyPropertiesStripeCustomerId, "properties-stripe-customer-id", "", "Stripe customer id")
	cmd.Flags().StringVar(&bodyPropertiesUsageDashboardLink, "properties-usage-dashboard-link", "", "Usage dashboard link")
	cmd.Flags().StringVar(&bodyPropertiesZendeskId, "properties-zendesk-id", "", "Zendesk id")
	cmd.Flags().StringVar(&bodySlackSummaryCadence, "slack-summary-cadence", "", "How often to generate an AI summary of the account's bound Slack channel (daily, weekly, or monthly).")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Tag names attached to the account. Pass a list to replace existing tags.")
	cmd.Flags().StringVar(&bodyUpdatedAt, "updated-at", "", "Updated at")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
