// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAlertsPartialUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyCalculationInterval string
	var bodyChecks string
	var bodyChecksTotal int
	var bodyCondition string
	var bodyConfig string
	var bodyCreatedAt string
	var bodyCreatedByDistinctId string
	var bodyCreatedByEmail string
	var bodyCreatedByFirstName string
	var bodyCreatedByHedgehogConfig string
	var bodyCreatedById string
	var bodyCreatedByIsEmailVerified bool
	var bodyCreatedByLastName string
	var bodyCreatedByRoleAtOrganization string
	var bodyCreatedByUuid string
	var bodyDetectorConfig string
	var bodyEnabled bool
	var bodyId2 string
	var bodyInsight int
	var bodyInvestigationAgentEnabled bool
	var bodyInvestigationGatesNotifications bool
	var bodyInvestigationInconclusiveAction string
	var bodyLastCheckedAt string
	var bodyLastNotifiedAt string
	var bodyLastValue float64
	var bodyName string
	var bodyNextCheckAt string
	var bodyScheduleRestriction string
	var bodySearchMatchType string
	var bodySkipWeekend bool
	var bodySnoozedUntil string
	var bodyState string
	var bodySubscribedUsers string
	var bodyThresholdConfigurationBounds string
	var bodyThresholdConfigurationType string
	var bodyThresholdCreatedAt string
	var bodyThresholdId string
	var bodyThresholdName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "partial-update <project_id> <id>",
		Short:       "Partial update",
		Example:     "  posthog-pp-cli alerts partial-update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "alerts.partial-update", "pp:method": "PATCH", "pp:path": "/api/projects/{project_id}/alerts/{id}/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <id>"))
			}
			if !stdinBody {
				if bodyCreatedByDistinctId != "" || bodyCreatedByEmail != "" || bodyCreatedByFirstName != "" || bodyCreatedByHedgehogConfig != "" || bodyCreatedById != "" || cmd.Flags().Changed("created-by-is-email-verified") || bodyCreatedByLastName != "" || bodyCreatedByRoleAtOrganization != "" || bodyCreatedByUuid != "" {
					if !cmd.Flags().Changed("created-by-email") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "created-by-email")
					}
					if !cmd.Flags().Changed("created-by-hedgehog-config") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "created-by-hedgehog-config")
					}
					if !cmd.Flags().Changed("created-by-id") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "created-by-id")
					}
					if !cmd.Flags().Changed("created-by-uuid") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "created-by-uuid")
					}
				}
				if bodyThresholdConfigurationBounds != "" || bodyThresholdConfigurationType != "" || bodyThresholdCreatedAt != "" || bodyThresholdId != "" || bodyThresholdName != "" {
					if !cmd.Flags().Changed("threshold-configuration-type") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "threshold-configuration-type")
					}
					if !cmd.Flags().Changed("threshold-created-at") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "threshold-created-at")
					}
					if !cmd.Flags().Changed("threshold-id") && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "threshold-id")
					}
				}
			}
			path := "/api/projects/{project_id}/alerts/{id}/"
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyCalculationInterval != "" {
					bodyMap["calculation_interval"] = bodyCalculationInterval
				}
				if bodyChecks != "" {
					var parsedChecks any
					if err := json.Unmarshal([]byte(bodyChecks), &parsedChecks); err != nil {
						return fmt.Errorf("parsing --checks JSON: %w", err)
					}
					asArray, ok := parsedChecks.([]any)
					if !ok {
						return fmt.Errorf("--checks must be a JSON array, got JSON %T", parsedChecks)
					}
					bodyMap["checks"] = asArray
				}
				if bodyChecksTotal != 0 {
					bodyMap["checks_total"] = bodyChecksTotal
				}
				if bodyCondition != "" {
					if looksLikeJSONComposite(bodyCondition) {
						var parsedCondition any
						if err := json.Unmarshal([]byte(bodyCondition), &parsedCondition); err != nil {
							return fmt.Errorf("parsing --condition JSON: %w", err)
						}
						bodyMap["condition"] = parsedCondition
					} else {
						bodyMap["condition"] = bodyCondition
					}
				}
				if bodyConfig != "" {
					if looksLikeJSONComposite(bodyConfig) {
						var parsedConfig any
						if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
							return fmt.Errorf("parsing --config JSON: %w", err)
						}
						bodyMap["config"] = parsedConfig
					} else {
						bodyMap["config"] = bodyConfig
					}
				}
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				{
					nestedCreatedBy := map[string]any{}
					if bodyCreatedByDistinctId != "" {
						nestedCreatedBy["distinct_id"] = bodyCreatedByDistinctId
					}
					if bodyCreatedByEmail != "" {
						nestedCreatedBy["email"] = bodyCreatedByEmail
					}
					if bodyCreatedByFirstName != "" {
						nestedCreatedBy["first_name"] = bodyCreatedByFirstName
					}
					if bodyCreatedByHedgehogConfig != "" {
						var parsedCreatedByHedgehogConfig any
						if err := json.Unmarshal([]byte(bodyCreatedByHedgehogConfig), &parsedCreatedByHedgehogConfig); err != nil {
							return fmt.Errorf("parsing --created-by-hedgehog-config JSON: %w", err)
						}
						asMap, ok := parsedCreatedByHedgehogConfig.(map[string]any)
						if !ok {
							return fmt.Errorf("--created-by-hedgehog-config must be a JSON object, got JSON %T", parsedCreatedByHedgehogConfig)
						}
						nestedCreatedBy["hedgehog_config"] = asMap
					}
					if bodyCreatedById != "" {
						nestedCreatedBy["id"] = bodyCreatedById
					}
					if cmd.Flags().Changed("created-by-is-email-verified") {
						nestedCreatedBy["is_email_verified"] = bodyCreatedByIsEmailVerified
					}
					if bodyCreatedByLastName != "" {
						nestedCreatedBy["last_name"] = bodyCreatedByLastName
					}
					if bodyCreatedByRoleAtOrganization != "" {
						nestedCreatedBy["role_at_organization"] = bodyCreatedByRoleAtOrganization
					}
					if bodyCreatedByUuid != "" {
						nestedCreatedBy["uuid"] = bodyCreatedByUuid
					}
					if len(nestedCreatedBy) > 0 {
						bodyMap["created_by"] = nestedCreatedBy
					}
				}
				if bodyDetectorConfig != "" {
					if looksLikeJSONComposite(bodyDetectorConfig) {
						var parsedDetectorConfig any
						if err := json.Unmarshal([]byte(bodyDetectorConfig), &parsedDetectorConfig); err != nil {
							return fmt.Errorf("parsing --detector-config JSON: %w", err)
						}
						bodyMap["detector_config"] = parsedDetectorConfig
					} else {
						bodyMap["detector_config"] = bodyDetectorConfig
					}
				}
				if cmd.Flags().Changed("enabled") {
					bodyMap["enabled"] = bodyEnabled
				}
				if bodyId2 != "" {
					bodyMap["id"] = bodyId2
				}
				if bodyInsight != 0 {
					bodyMap["insight"] = bodyInsight
				}
				if cmd.Flags().Changed("investigation-agent-enabled") {
					bodyMap["investigation_agent_enabled"] = bodyInvestigationAgentEnabled
				}
				if cmd.Flags().Changed("investigation-gates-notifications") {
					bodyMap["investigation_gates_notifications"] = bodyInvestigationGatesNotifications
				}
				if bodyInvestigationInconclusiveAction != "" {
					bodyMap["investigation_inconclusive_action"] = bodyInvestigationInconclusiveAction
				}
				if bodyLastCheckedAt != "" {
					bodyMap["last_checked_at"] = bodyLastCheckedAt
				}
				if bodyLastNotifiedAt != "" {
					bodyMap["last_notified_at"] = bodyLastNotifiedAt
				}
				if bodyLastValue != 0.0 {
					bodyMap["last_value"] = bodyLastValue
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if bodyNextCheckAt != "" {
					bodyMap["next_check_at"] = bodyNextCheckAt
				}
				if bodyScheduleRestriction != "" {
					if looksLikeJSONComposite(bodyScheduleRestriction) {
						var parsedScheduleRestriction any
						if err := json.Unmarshal([]byte(bodyScheduleRestriction), &parsedScheduleRestriction); err != nil {
							return fmt.Errorf("parsing --schedule-restriction JSON: %w", err)
						}
						bodyMap["schedule_restriction"] = parsedScheduleRestriction
					} else {
						bodyMap["schedule_restriction"] = bodyScheduleRestriction
					}
				}
				if bodySearchMatchType != "" {
					bodyMap["search_match_type"] = bodySearchMatchType
				}
				if cmd.Flags().Changed("skip-weekend") {
					bodyMap["skip_weekend"] = bodySkipWeekend
				}
				if bodySnoozedUntil != "" {
					bodyMap["snoozed_until"] = bodySnoozedUntil
				}
				if bodyState != "" {
					bodyMap["state"] = bodyState
				}
				if bodySubscribedUsers != "" {
					var parsedSubscribedUsers any
					if err := json.Unmarshal([]byte(bodySubscribedUsers), &parsedSubscribedUsers); err != nil {
						return fmt.Errorf("parsing --subscribed-users JSON: %w", err)
					}
					asArray, ok := parsedSubscribedUsers.([]any)
					if !ok {
						return fmt.Errorf("--subscribed-users must be a JSON array, got JSON %T", parsedSubscribedUsers)
					}
					bodyMap["subscribed_users"] = asArray
				}
				{
					nestedThreshold := map[string]any{}
					{
						nestedThresholdConfiguration := map[string]any{}
						if bodyThresholdConfigurationBounds != "" {
							if looksLikeJSONComposite(bodyThresholdConfigurationBounds) {
								var parsedThresholdConfigurationBounds any
								if err := json.Unmarshal([]byte(bodyThresholdConfigurationBounds), &parsedThresholdConfigurationBounds); err != nil {
									return fmt.Errorf("parsing --threshold-configuration-bounds JSON: %w", err)
								}
								nestedThresholdConfiguration["bounds"] = parsedThresholdConfigurationBounds
							} else {
								nestedThresholdConfiguration["bounds"] = bodyThresholdConfigurationBounds
							}
						}
						if bodyThresholdConfigurationType != "" {
							nestedThresholdConfiguration["type"] = bodyThresholdConfigurationType
						}
						if len(nestedThresholdConfiguration) > 0 {
							nestedThreshold["configuration"] = nestedThresholdConfiguration
						}
					}
					if bodyThresholdCreatedAt != "" {
						nestedThreshold["created_at"] = bodyThresholdCreatedAt
					}
					if bodyThresholdId != "" {
						nestedThreshold["id"] = bodyThresholdId
					}
					if bodyThresholdName != "" {
						nestedThreshold["name"] = bodyThresholdName
					}
					if len(nestedThreshold) > 0 {
						bodyMap["threshold"] = nestedThreshold
					}
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "alerts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "alerts", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "alerts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "alerts", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCalculationInterval, "calculation-interval", "", "How often the alert is checked: real time (Scale+), every 15 minutes (Boost+), hourly, daily, weekly, or monthly.")
	cmd.Flags().StringVar(&bodyChecks, "checks", "", "Alert check results. By default returns the last 5. Use checks_date_from and checks_date_to (e.g.")
	cmd.Flags().IntVar(&bodyChecksTotal, "checks-total", 0, "Total alert checks matching the retrieve filters (date window). Only set on alert retrieve; omitted otherwise.")
	cmd.Flags().StringVar(&bodyCondition, "condition", "", "Alert condition type. Determines how the value is evaluated: absolute_value, relative_increase, or relative_decrease.")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "Per-insight-kind alert configuration, discriminated by `type`.")
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyCreatedByDistinctId, "created-by-distinct-id", "", "Distinct id")
	cmd.Flags().StringVar(&bodyCreatedByEmail, "created-by-email", "", "Email")
	cmd.Flags().StringVar(&bodyCreatedByFirstName, "created-by-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyCreatedByHedgehogConfig, "created-by-hedgehog-config", "", "Hedgehog config")
	cmd.Flags().StringVar(&bodyCreatedById, "created-by-id", "", "Id")
	cmd.Flags().BoolVar(&bodyCreatedByIsEmailVerified, "created-by-is-email-verified", false, "Is email verified")
	cmd.Flags().StringVar(&bodyCreatedByLastName, "created-by-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyCreatedByRoleAtOrganization, "created-by-role-at-organization", "", "Role at organization")
	cmd.Flags().StringVar(&bodyCreatedByUuid, "created-by-uuid", "", "Uuid")
	cmd.Flags().StringVar(&bodyDetectorConfig, "detector-config", "", "Detector config")
	cmd.Flags().BoolVar(&bodyEnabled, "enabled", false, "Whether the alert is actively being evaluated.")
	cmd.Flags().StringVar(&bodyId2, "id-2", "", "Id")
	cmd.Flags().IntVar(&bodyInsight, "insight", 0, "Insight ID monitored by this alert. Note: Response returns full InsightBasicSerializer object.")
	cmd.Flags().BoolVar(&bodyInvestigationAgentEnabled, "investigation-agent-enabled", false, "When enabled")
	cmd.Flags().BoolVar(&bodyInvestigationGatesNotifications, "investigation-gates-notifications", false, "When enabled (and investigation_agent_enabled is on)")
	cmd.Flags().StringVar(&bodyInvestigationInconclusiveAction, "investigation-inconclusive-action", "", "How to handle an 'inconclusive' verdict")
	cmd.Flags().StringVar(&bodyLastCheckedAt, "last-checked-at", "", "Last checked at")
	cmd.Flags().StringVar(&bodyLastNotifiedAt, "last-notified-at", "", "Last notified at")
	cmd.Flags().Float64Var(&bodyLastValue, "last-value", 0.0, "The last calculated value from the most recent alert check.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Human-readable name for the alert.")
	cmd.Flags().StringVar(&bodyNextCheckAt, "next-check-at", "", "Next check at")
	cmd.Flags().StringVar(&bodyScheduleRestriction, "schedule-restriction", "", "Blocked local time windows (HH:MM in the project timezone).")
	cmd.Flags().StringVar(&bodySearchMatchType, "search-match-type", "", "How this row matched the `search` query parameter")
	cmd.Flags().BoolVar(&bodySkipWeekend, "skip-weekend", false, "Skip alert evaluation on weekends (Saturday and Sunday, local to project timezone).")
	cmd.Flags().StringVar(&bodySnoozedUntil, "snoozed-until", "", "Snooze the alert until this time. Pass a relative date string (e.g. '2h', '1d') or null to unsnooze.")
	cmd.Flags().StringVar(&bodyState, "state", "", "Current alert state: Firing, Not firing, Errored, or Snoozed.")
	cmd.Flags().StringVar(&bodySubscribedUsers, "subscribed-users", "", "User IDs to subscribe to this alert. Note: Response returns full UserBasicSerializer object.")
	cmd.Flags().StringVar(&bodyThresholdConfigurationBounds, "threshold-configuration-bounds", "", "Bounds")
	cmd.Flags().StringVar(&bodyThresholdConfigurationType, "threshold-configuration-type", "", "Whether bounds are compared as absolute values or as percentage change from the previous interval.")
	cmd.Flags().StringVar(&bodyThresholdCreatedAt, "threshold-created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyThresholdId, "threshold-id", "", "Id")
	cmd.Flags().StringVar(&bodyThresholdName, "threshold-name", "", "Optional name for the threshold.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
