// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCanvasesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "canvases",
		Short:       "List, get, create, update, and delete canvases",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCanvasesCreateCmd(flags))
	cmd.AddCommand(newCanvasesDestroyCmd(flags))
	cmd.AddCommand(newCanvasesListCmd(flags))
	cmd.AddCommand(newCanvasesPartialUpdateCmd(flags))
	cmd.AddCommand(newCanvasesRetrieveCmd(flags))
	cmd.AddCommand(newCanvasesBuildsCmd(flags))
	cmd.AddCommand(newCanvasesEditCmd(flags))
	cmd.AddCommand(newCanvasesPublishCmd(flags))
	cmd.AddCommand(newCanvasesRevertCmd(flags))
	cmd.AddCommand(newCanvasesSourceCmd(flags))
	cmd.AddCommand(newCanvasesValidateCmd(flags))
	cmd.AddCommand(newCanvasesVersionsCmd(flags))
	return cmd
}
