// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCohortsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "cohorts",
		Short:       "List, get, create, update, and delete cohorts",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCohortsAllActivityRetrieveCmd(flags))
	cmd.AddCommand(newCohortsCreateCmd(flags))
	cmd.AddCommand(newCohortsDestroyCmd(flags))
	cmd.AddCommand(newCohortsListCmd(flags))
	cmd.AddCommand(newCohortsPartialUpdateCmd(flags))
	cmd.AddCommand(newCohortsRetrieveCmd(flags))
	cmd.AddCommand(newCohortsUpdateCmd(flags))
	cmd.AddCommand(newCohortsActivityCmd(flags))
	cmd.AddCommand(newCohortsAddPersonsToStaticCohortCmd(flags))
	cmd.AddCommand(newCohortsCalculationHistoryCmd(flags))
	cmd.AddCommand(newCohortsPersonsCmd(flags))
	cmd.AddCommand(newCohortsRemovePersonFromStaticCohortCmd(flags))
	cmd.AddCommand(newCohortsUsedInCmd(flags))
	return cmd
}
