// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCommentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "comments",
		Short:       "List, get, count, create, update, and delete comments",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCommentsCountRetrieveCmd(flags))
	cmd.AddCommand(newCommentsCreateCmd(flags))
	cmd.AddCommand(newCommentsDestroyCmd(flags))
	cmd.AddCommand(newCommentsListCmd(flags))
	cmd.AddCommand(newCommentsPartialUpdateCmd(flags))
	cmd.AddCommand(newCommentsRetrieveCmd(flags))
	cmd.AddCommand(newCommentsUpdateCmd(flags))
	cmd.AddCommand(newCommentsCompleteCmd(flags))
	cmd.AddCommand(newCommentsReopenCmd(flags))
	cmd.AddCommand(newCommentsSendToSlackCmd(flags))
	cmd.AddCommand(newCommentsThreadCmd(flags))
	return cmd
}
