// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardsRunInsightsDashboardsRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagFiltersOverride string
	var flagFormat string
	var flagOutputFormat string
	var flagRefresh string
	var flagVariablesOverride string

	cmd := &cobra.Command{
		Use:         "dashboards-retrieve <project_id> <id>",
		Aliases:     []string{"get"},
		Short:       "Run all insights on a dashboard and return their results.",
		Example:     "  posthog-pp-cli dashboards run-insights dashboards-retrieve 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "run-insights.dashboards-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/dashboards/{id}/run_insights/", "mcp:read-only": "true", "pp:requires-tier": "streaming"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <id>"))
			}
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"json", "txt"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFormat, "format", allowedFormat)
				}
			}
			if cmd.Flags().Changed("output-format") {
				allowedOutputFormat := []string{"json", "optimized"}
				validOutputFormat := false
				for _, v := range allowedOutputFormat {
					if flagOutputFormat == v {
						validOutputFormat = true
						break
					}
				}
				if !validOutputFormat {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagOutputFormat, "output-format", allowedOutputFormat)
				}
			}
			if cmd.Flags().Changed("refresh") {
				allowedRefresh := []string{"blocking", "force_blocking", "force_cache"}
				validRefresh := false
				for _, v := range allowedRefresh {
					if flagRefresh == v {
						validRefresh = true
						break
					}
				}
				if !validRefresh {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagRefresh, "refresh", allowedRefresh)
				}
			}
			path := "/api/projects/{project_id}/dashboards/{id}/run_insights/"
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagFiltersOverride != "" {
				params["filters_override"] = formatCLIParamValue(flagFiltersOverride)
			}
			if flagFormat != "" {
				params["format"] = formatCLIParamValue(flagFormat)
			}
			if flagOutputFormat != "" {
				params["output_format"] = formatCLIParamValue(flagOutputFormat)
			}
			if flagRefresh != "" {
				params["refresh"] = formatCLIParamValue(flagRefresh)
			}
			if flagVariablesOverride != "" {
				params["variables_override"] = formatCLIParamValue(flagVariablesOverride)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "run-insights", false, path, params, nil, "results", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagFiltersOverride, "filters-override", "", "Object (or pre-encoded JSON string) to override dashboard filters for this request only (not persisted).")
	cmd.Flags().StringVar(&flagFormat, "format", "", "Format (one of: json, txt)")
	cmd.Flags().StringVar(&flagOutputFormat, "output-format", "", "'optimized' (default) returns LLM-friendly formatted text per insight. 'json' returns the raw query result objects. (one of: json, optimized)")
	cmd.Flags().StringVar(&flagRefresh, "refresh", "", "Cache behavior. 'force_cache' (default) serves from cache even if stale. (one of: blocking, force_blocking, force_cache)")
	cmd.Flags().StringVar(&flagVariablesOverride, "variables-override", "", "Object (or pre-encoded JSON string) to override dashboard variables for this request only (not persisted).")

	return cmd
}
