// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDashboardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dashboards",
		Short:       "List, get, create, update, and delete dashboards",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDashboardsBulkUpdateTagsCreateCmd(flags))
	cmd.AddCommand(newDashboardsCreateCmd(flags))
	cmd.AddCommand(newDashboardsCreateFromTemplateJsonCreateCmd(flags))
	cmd.AddCommand(newDashboardsCreateUnlistedCreateCmd(flags))
	cmd.AddCommand(newDashboardsDestroyCmd(flags))
	cmd.AddCommand(newDashboardsListCmd(flags))
	cmd.AddCommand(newDashboardsPartialUpdateCmd(flags))
	cmd.AddCommand(newDashboardsRetrieveCmd(flags))
	cmd.AddCommand(newDashboardsUpdateCmd(flags))
	cmd.AddCommand(newDashboardsWidgetCatalogRetrieveCmd(flags))
	cmd.AddCommand(newDashboardsCollaboratorsCmd(flags))
	cmd.AddCommand(newDashboardsCopyTileCmd(flags))
	cmd.AddCommand(newDashboardsCreateTextTileCmd(flags))
	cmd.AddCommand(newDashboardsDeleteTileCmd(flags))
	cmd.AddCommand(newDashboardsMoveTileCmd(flags))
	cmd.AddCommand(newDashboardsReorderTilesCmd(flags))
	cmd.AddCommand(newDashboardsRunInsightsCmd(flags))
	cmd.AddCommand(newDashboardsRunWidgetsCmd(flags))
	cmd.AddCommand(newDashboardsSharingCmd(flags))
	cmd.AddCommand(newDashboardsStreamTilesCmd(flags))
	cmd.AddCommand(newDashboardsSubscribeNudgeCmd(flags))
	cmd.AddCommand(newDashboardsUpdateTextTileCmd(flags))
	cmd.AddCommand(newDashboardsWidgetsCmd(flags))
	return cmd
}
