// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEarlyAccessFeatureCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "early-access-feature",
		Short:       "Manage early access feature",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEarlyAccessFeatureCreateCmd(flags))
	cmd.AddCommand(newEarlyAccessFeatureDestroyCmd(flags))
	cmd.AddCommand(newEarlyAccessFeatureListCmd(flags))
	cmd.AddCommand(newEarlyAccessFeaturePartialUpdateCmd(flags))
	cmd.AddCommand(newEarlyAccessFeatureRetrieveCmd(flags))
	cmd.AddCommand(newEarlyAccessFeatureUpdateCmd(flags))
	return cmd
}
