// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newElementsStatsRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagDataAttributes string
	var flagDateFrom string
	var flagDateTo string
	var flagFilterTestAccounts bool
	var flagInclude string
	var flagLimit int
	var flagOffset string
	var flagProperties string
	var flagSamplingFactor float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "stats-retrieve <project_id>",
		Short:       "Counts of $autocapture, $rageclick, and $dead_click events grouped by the element chain they occurred on",
		Example:     "  posthog-pp-cli elements stats-retrieve 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "elements.stats-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/elements/stats/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if cmd.Flags().Changed("properties") {
				var parsedProperties any
				if err := json.Unmarshal([]byte(flagProperties), &parsedProperties); err != nil {
					return fmt.Errorf("--properties must be valid JSON: %w", err)
				}
			}
			path := "/api/projects/{project_id}/elements/stats/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if flagInclude != "" {
				path = appendArrayQueryParam(path, "include", flagInclude, "form", true)
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "elements", path, map[string]string{
				"data_attributes":      formatCLIParamValue(flagDataAttributes),
				"date_from":            formatCLIParamValue(flagDateFrom),
				"date_to":              formatCLIParamValue(flagDateTo),
				"filter_test_accounts": formatCLIParamValue(flagFilterTestAccounts),
				"limit":                formatCLIParamValue(flagLimit),
				"offset":               formatCLIParamValue(flagOffset),
				"properties":           formatCLIParamValue(flagProperties),
				"sampling_factor":      formatCLIParamValue(flagSamplingFactor),
			}, nil, flagAll, "offset", "offset", "limit", 100, "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagDataAttributes, "data-attributes", "", "Comma-separated data attribute names (wildcards allowed, e.g. data-*).")
	cmd.Flags().StringVar(&flagDateFrom, "date-from", "", "Start of the date range (e.g. -7d, 2024-01-01). Defaults to last 7 days.")
	cmd.Flags().StringVar(&flagDateTo, "date-to", "", "End of the date range (e.g. 2024-01-31). Defaults to now.")
	cmd.Flags().BoolVar(&flagFilterTestAccounts, "filter-test-accounts", false, "When true, applies the project's internal-and-test-account filters to the underlying events.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Event types to include: $autocapture, $rageclick, $dead_click. Defaults to all three.")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum rows per page")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Pagination offset")
	cmd.Flags().StringVar(&flagProperties, "properties", "", "JSON-encoded list of property filters to apply to the underlying events, e.g.")
	cmd.Flags().Float64Var(&flagSamplingFactor, "sampling-factor", 0.0, "Sampling factor between 0 and 1")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
