// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"
)

func newEngineeringAnalyticsWorkflowJobsCmd(flags *rootFlags) *cobra.Command {
	var flagRepo string
	var flagRunAttempt int
	var flagRunId string
	var flagSourceId string
	var flagWait bool
	var flagWaitTimeout time.Duration
	var flagWaitInterval time.Duration

	cmd := &cobra.Command{
		Use:         "workflow-jobs <project_id>",
		Short:       "Jobs of a single workflow run attempt, with per-job duration, runner tier, and estimated cost.",
		Example:     "  posthog-pp-cli engineering-analytics workflow-jobs 550e8400-e29b-41d4-a716-446655440000 --run-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "engineering-analytics.workflow-jobs", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/engineering_analytics/workflow_jobs/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !cmd.Flags().Changed("run-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "run-id")
			}
			path := "/api/projects/{project_id}/engineering_analytics/workflow_jobs/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagRepo != "" {
				params["repo"] = formatCLIParamValue(flagRepo)
			}
			if flagRunAttempt != 0 {
				params["run_attempt"] = formatCLIParamValue(flagRunAttempt)
			}
			if flagRunId != "" {
				params["run_id"] = formatCLIParamValue(flagRunId)
			}
			if flagSourceId != "" {
				params["source_id"] = formatCLIParamValue(flagSourceId)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "engineering-analytics", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if asyncJobID := ExtractJobID(data, "run_id"); asyncJobID != "" {
				_ = RecordJob(JobRow{
					JobID:          asyncJobID,
					Resource:       "engineering-analytics",
					Endpoint:       "workflow-jobs",
					Status:         "submitted",
					StatusResource: "data-modeling-jobs",
					StatusEndpoint: "recent-retrieve",
				})
				if flagWait {
					ctx := cmd.Context()
					if ctx == nil {
						ctx = context.Background()
					}
					final, werr := WaitForJob(ctx, c, "/api/projects/{project_id}/data_modeling_jobs/recent/", asyncJobID, WaitOptions{
						Interval: flagWaitInterval,
						Timeout:  flagWaitTimeout,
					})
					if werr != nil {
						_ = RecordJob(JobRow{
							JobID:    asyncJobID,
							Resource: "engineering-analytics",
							Endpoint: "workflow-jobs",
							Status:   "errored",
							Error:    werr.Error(),
						})
						return werr
					}
					if b, merr := json.Marshal(final); merr == nil {
						data = b
					}
					if st, _ := final["status"].(string); st != "" {
						_ = RecordJob(JobRow{
							JobID:    asyncJobID,
							Resource: "engineering-analytics",
							Endpoint: "workflow-jobs",
							Status:   st,
						})
					}
				}
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagRepo, "repo", "", "'owner/name' repository to scope to when the selected source syncs several repositories (from the `sources` list).")
	cmd.Flags().IntVar(&flagRunAttempt, "run-attempt", 0, "Which re-run attempt to scope jobs to.")
	cmd.Flags().StringVar(&flagRunId, "run-id", "", "Workflow run id to list jobs for.")
	cmd.Flags().StringVar(&flagSourceId, "source-id", "", "Connected GitHub data warehouse source to read from.")
	cmd.Flags().BoolVar(&flagWait, "wait", false, "Block until the submitted job reaches a terminal status")
	cmd.Flags().DurationVar(&flagWaitTimeout, "wait-timeout", 10*time.Minute, "Maximum duration to wait when --wait is set (0 = no timeout)")
	cmd.Flags().DurationVar(&flagWaitInterval, "wait-interval", 2*time.Second, "Initial poll interval when --wait is set")

	return cmd
}
