// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEngineeringAnalyticsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "engineering-analytics",
		Short:       "Get, run, create, and update engineering analytics",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEngineeringAnalyticsAuthorWorkflowCostsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsBrokenTestsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsCiCardsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsCiFailureLogsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsCiSignalsConfigRetrieveCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsCiSignalsConfigUpdateCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsCurrentBranchHealthCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsFlakyTestsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsJobAggregatesCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsMasterFailuresCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsPrCostCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsPrLifecycleCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsPrRunsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsPullRequestsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsQuarantineCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsQuarantineRequestCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsRepoOverviewCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsRepoRunActivityCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsResolveBranchCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsRunFailureLogsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsSourcesCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsTeamCiActivityCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsTeamCiHealthCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsTeamMergeTrendCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowHealthCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowJobsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowRunCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowRunActivityCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowRunnerCostsCmd(flags))
	cmd.AddCommand(newEngineeringAnalyticsWorkflowRunsCmd(flags))
	return cmd
}
