// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newEventSchemasCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyCreatedAt string
	var bodyEventDefinition string
	var bodyId string
	var bodyPropertyGroupCreatedAt string
	var bodyPropertyGroupCreatedByDistinctId string
	var bodyPropertyGroupCreatedByEmail string
	var bodyPropertyGroupCreatedByFirstName string
	var bodyPropertyGroupCreatedByHedgehogConfig string
	var bodyPropertyGroupCreatedById string
	var bodyPropertyGroupCreatedByIsEmailVerified bool
	var bodyPropertyGroupCreatedByLastName string
	var bodyPropertyGroupCreatedByRoleAtOrganization string
	var bodyPropertyGroupCreatedByUuid string
	var bodyPropertyGroupDescription string
	var bodyPropertyGroupEvents string
	var bodyPropertyGroupId string
	var bodyPropertyGroupName string
	var bodyPropertyGroupProperties string
	var bodyPropertyGroupUpdatedAt string
	var bodyPropertyGroupId2 string
	var bodyUpdatedAt string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <project_id>",
		Short:       "Create",
		Example:     "  posthog-pp-cli event-schemas create 550e8400-e29b-41d4-a716-446655440000 --created-at 2026-01-15T09:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "event-schemas.create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/event_schemas/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-at")
				}
				if !cmd.Flags().Changed("event-definition") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "event-definition")
				}
				if !cmd.Flags().Changed("id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "id")
				}
				if !cmd.Flags().Changed("property-group-created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-created-at")
				}
				if !cmd.Flags().Changed("property-group-created-by-email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-created-by-email")
				}
				if !cmd.Flags().Changed("property-group-created-by-hedgehog-config") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-created-by-hedgehog-config")
				}
				if !cmd.Flags().Changed("property-group-created-by-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-created-by-id")
				}
				if !cmd.Flags().Changed("property-group-created-by-uuid") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-created-by-uuid")
				}
				if !cmd.Flags().Changed("property-group-events") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-events")
				}
				if !cmd.Flags().Changed("property-group-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-id")
				}
				if !cmd.Flags().Changed("property-group-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-name")
				}
				if !cmd.Flags().Changed("property-group-updated-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-updated-at")
				}
				if !cmd.Flags().Changed("property-group-id-2") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "property-group-id-2")
				}
				if !cmd.Flags().Changed("updated-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "updated-at")
				}
			}
			path := "/api/projects/{project_id}/event_schemas/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				if bodyEventDefinition != "" {
					bodyMap["event_definition"] = bodyEventDefinition
				}
				if bodyId != "" {
					bodyMap["id"] = bodyId
				}
				{
					nestedPropertyGroup := map[string]any{}
					if bodyPropertyGroupCreatedAt != "" {
						nestedPropertyGroup["created_at"] = bodyPropertyGroupCreatedAt
					}
					{
						nestedPropertyGroupCreatedBy := map[string]any{}
						if bodyPropertyGroupCreatedByDistinctId != "" {
							nestedPropertyGroupCreatedBy["distinct_id"] = bodyPropertyGroupCreatedByDistinctId
						}
						if bodyPropertyGroupCreatedByEmail != "" {
							nestedPropertyGroupCreatedBy["email"] = bodyPropertyGroupCreatedByEmail
						}
						if bodyPropertyGroupCreatedByFirstName != "" {
							nestedPropertyGroupCreatedBy["first_name"] = bodyPropertyGroupCreatedByFirstName
						}
						if bodyPropertyGroupCreatedByHedgehogConfig != "" {
							var parsedPropertyGroupCreatedByHedgehogConfig any
							if err := json.Unmarshal([]byte(bodyPropertyGroupCreatedByHedgehogConfig), &parsedPropertyGroupCreatedByHedgehogConfig); err != nil {
								return fmt.Errorf("parsing --property-group-created-by-hedgehog-config JSON: %w", err)
							}
							asMap, ok := parsedPropertyGroupCreatedByHedgehogConfig.(map[string]any)
							if !ok {
								return fmt.Errorf("--property-group-created-by-hedgehog-config must be a JSON object, got JSON %T", parsedPropertyGroupCreatedByHedgehogConfig)
							}
							nestedPropertyGroupCreatedBy["hedgehog_config"] = asMap
						}
						if bodyPropertyGroupCreatedById != "" {
							nestedPropertyGroupCreatedBy["id"] = bodyPropertyGroupCreatedById
						}
						if cmd.Flags().Changed("property-group-created-by-is-email-verified") {
							nestedPropertyGroupCreatedBy["is_email_verified"] = bodyPropertyGroupCreatedByIsEmailVerified
						}
						if bodyPropertyGroupCreatedByLastName != "" {
							nestedPropertyGroupCreatedBy["last_name"] = bodyPropertyGroupCreatedByLastName
						}
						if bodyPropertyGroupCreatedByRoleAtOrganization != "" {
							nestedPropertyGroupCreatedBy["role_at_organization"] = bodyPropertyGroupCreatedByRoleAtOrganization
						}
						if bodyPropertyGroupCreatedByUuid != "" {
							nestedPropertyGroupCreatedBy["uuid"] = bodyPropertyGroupCreatedByUuid
						}
						if len(nestedPropertyGroupCreatedBy) > 0 {
							nestedPropertyGroup["created_by"] = nestedPropertyGroupCreatedBy
						}
					}
					if bodyPropertyGroupDescription != "" {
						nestedPropertyGroup["description"] = bodyPropertyGroupDescription
					}
					if bodyPropertyGroupEvents != "" {
						var parsedPropertyGroupEvents any
						if err := json.Unmarshal([]byte(bodyPropertyGroupEvents), &parsedPropertyGroupEvents); err != nil {
							return fmt.Errorf("parsing --property-group-events JSON: %w", err)
						}
						asArray, ok := parsedPropertyGroupEvents.([]any)
						if !ok {
							return fmt.Errorf("--property-group-events must be a JSON array, got JSON %T", parsedPropertyGroupEvents)
						}
						nestedPropertyGroup["events"] = asArray
					}
					if bodyPropertyGroupId != "" {
						nestedPropertyGroup["id"] = bodyPropertyGroupId
					}
					if bodyPropertyGroupName != "" {
						nestedPropertyGroup["name"] = bodyPropertyGroupName
					}
					if bodyPropertyGroupProperties != "" {
						var parsedPropertyGroupProperties any
						if err := json.Unmarshal([]byte(bodyPropertyGroupProperties), &parsedPropertyGroupProperties); err != nil {
							return fmt.Errorf("parsing --property-group-properties JSON: %w", err)
						}
						asArray, ok := parsedPropertyGroupProperties.([]any)
						if !ok {
							return fmt.Errorf("--property-group-properties must be a JSON array, got JSON %T", parsedPropertyGroupProperties)
						}
						nestedPropertyGroup["properties"] = asArray
					}
					if bodyPropertyGroupUpdatedAt != "" {
						nestedPropertyGroup["updated_at"] = bodyPropertyGroupUpdatedAt
					}
					if len(nestedPropertyGroup) > 0 {
						bodyMap["property_group"] = nestedPropertyGroup
					}
				}
				if bodyPropertyGroupId2 != "" {
					bodyMap["property_group_id"] = bodyPropertyGroupId2
				}
				if bodyUpdatedAt != "" {
					bodyMap["updated_at"] = bodyUpdatedAt
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "event-schemas", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "event-schemas", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "event-schemas", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "event-schemas", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "event-schemas", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "event-schemas",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "event-schemas", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "event-schemas", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyEventDefinition, "event-definition", "", "Event definition")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedAt, "property-group-created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByDistinctId, "property-group-created-by-distinct-id", "", "Distinct id")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByEmail, "property-group-created-by-email", "", "Email")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByFirstName, "property-group-created-by-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByHedgehogConfig, "property-group-created-by-hedgehog-config", "", "Hedgehog config")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedById, "property-group-created-by-id", "", "Id")
	cmd.Flags().BoolVar(&bodyPropertyGroupCreatedByIsEmailVerified, "property-group-created-by-is-email-verified", false, "Is email verified")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByLastName, "property-group-created-by-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByRoleAtOrganization, "property-group-created-by-role-at-organization", "", "Role at organization")
	cmd.Flags().StringVar(&bodyPropertyGroupCreatedByUuid, "property-group-created-by-uuid", "", "Uuid")
	cmd.Flags().StringVar(&bodyPropertyGroupDescription, "property-group-description", "", "Description")
	cmd.Flags().StringVar(&bodyPropertyGroupEvents, "property-group-events", "", "Events")
	cmd.Flags().StringVar(&bodyPropertyGroupId, "property-group-id", "", "Id")
	cmd.Flags().StringVar(&bodyPropertyGroupName, "property-group-name", "", "Name")
	cmd.Flags().StringVar(&bodyPropertyGroupProperties, "property-group-properties", "", "Properties")
	cmd.Flags().StringVar(&bodyPropertyGroupUpdatedAt, "property-group-updated-at", "", "Updated at")
	cmd.Flags().StringVar(&bodyPropertyGroupId2, "property-group-id-2", "", "Property group id")
	cmd.Flags().StringVar(&bodyUpdatedAt, "updated-at", "", "Updated at")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
