// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEventSchemasCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "event-schemas",
		Short:       "List, create, update, and delete event schemas",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEventSchemasCreateCmd(flags))
	cmd.AddCommand(newEventSchemasDestroyCmd(flags))
	cmd.AddCommand(newEventSchemasListCmd(flags))
	cmd.AddCommand(newEventSchemasPartialUpdateCmd(flags))
	cmd.AddCommand(newEventSchemasUpdateCmd(flags))
	return cmd
}
