// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newExternalDataSourcesDeleteWebhookExternalDataSourcesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessMethod string
	var bodyAccountId string
	var bodyApiVersion string
	var bodyApiVersionDeprecation string
	var bodyAutoSyncNewSchemas bool
	var bodyAutoSyncSchemaPatterns string
	var bodyClientSecret string
	var bodyCreatedAt string
	var bodyCreatedBy string
	var bodyCreatedVia string
	var bodyDescription string
	var bodyDirectQueryEnabled bool
	var bodyEngine string
	var bodyId2 string
	var bodyJobInputs string
	var bodyLastRunAt string
	var bodyLatestError string
	var bodyPrefix string
	var bodyRevenueAnalyticsConfigEnabled bool
	var bodyRevenueAnalyticsConfigIncludeInvoicelessCharges bool
	var bodySchemas string
	var bodySourceType string
	var bodyStatus string
	var bodySupportsColumnSelection string
	var bodySupportsWebhooks string
	var bodyUserAccessLevel string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "external-data-sources-create <project_id> <id>",
		Aliases:     []string{"create"},
		Short:       "Create, Read, Update and Delete External data Sources.",
		Example:     "  posthog-pp-cli external-data-sources delete-webhook external-data-sources-create 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --access-method warehouse",
		Annotations: map[string]string{"pp:endpoint": "delete-webhook.external-data-sources-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/external_data_sources/{id}/delete_webhook/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("access-method") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "access-method")
				}
				if !cmd.Flags().Changed("account-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "account-id")
				}
				if !cmd.Flags().Changed("api-version") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "api-version")
				}
				if !cmd.Flags().Changed("api-version-deprecation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "api-version-deprecation")
				}
				if !cmd.Flags().Changed("client-secret") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-secret")
				}
				if !cmd.Flags().Changed("created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-at")
				}
				if !cmd.Flags().Changed("created-by") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by")
				}
				if !cmd.Flags().Changed("engine") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "engine")
				}
				if !cmd.Flags().Changed("id-2") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "id-2")
				}
				if !cmd.Flags().Changed("last-run-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "last-run-at")
				}
				if !cmd.Flags().Changed("latest-error") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "latest-error")
				}
				if !cmd.Flags().Changed("schemas") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "schemas")
				}
				if !cmd.Flags().Changed("source-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "source-type")
				}
				if !cmd.Flags().Changed("status") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status")
				}
				if !cmd.Flags().Changed("supports-column-selection") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "supports-column-selection")
				}
				if !cmd.Flags().Changed("supports-webhooks") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "supports-webhooks")
				}
				if !cmd.Flags().Changed("user-access-level") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "user-access-level")
				}
			}
			path := "/api/projects/{project_id}/external_data_sources/{id}/delete_webhook/"
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyAccessMethod != "" {
					bodyMap["access_method"] = bodyAccessMethod
				}
				if bodyAccountId != "" {
					bodyMap["account_id"] = bodyAccountId
				}
				if bodyApiVersion != "" {
					bodyMap["api_version"] = bodyApiVersion
				}
				if bodyApiVersionDeprecation != "" {
					if looksLikeJSONComposite(bodyApiVersionDeprecation) {
						var parsedApiVersionDeprecation any
						if err := json.Unmarshal([]byte(bodyApiVersionDeprecation), &parsedApiVersionDeprecation); err != nil {
							return fmt.Errorf("parsing --api-version-deprecation JSON: %w", err)
						}
						bodyMap["api_version_deprecation"] = parsedApiVersionDeprecation
					} else {
						bodyMap["api_version_deprecation"] = bodyApiVersionDeprecation
					}
				}
				if cmd.Flags().Changed("auto-sync-new-schemas") {
					bodyMap["auto_sync_new_schemas"] = bodyAutoSyncNewSchemas
				}
				if cmd.Flags().Changed("auto-sync-schema-patterns") {
					parsedAutoSyncSchemaPatterns, parseErr := cliutil.ParseStringList(bodyAutoSyncSchemaPatterns)
					if parseErr != nil {
						return fmt.Errorf("parsing --auto-sync-schema-patterns list: %w", parseErr)
					}
					bodyMap["auto_sync_schema_patterns"] = parsedAutoSyncSchemaPatterns
				}
				if bodyClientSecret != "" {
					bodyMap["client_secret"] = bodyClientSecret
				}
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				if bodyCreatedBy != "" {
					bodyMap["created_by"] = bodyCreatedBy
				}
				if bodyCreatedVia != "" {
					bodyMap["created_via"] = bodyCreatedVia
				}
				if bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if cmd.Flags().Changed("direct-query-enabled") {
					bodyMap["direct_query_enabled"] = bodyDirectQueryEnabled
				}
				if bodyEngine != "" {
					bodyMap["engine"] = bodyEngine
				}
				if bodyId2 != "" {
					bodyMap["id"] = bodyId2
				}
				if bodyJobInputs != "" {
					bodyMap["job_inputs"] = bodyJobInputs
				}
				if bodyLastRunAt != "" {
					bodyMap["last_run_at"] = bodyLastRunAt
				}
				if bodyLatestError != "" {
					bodyMap["latest_error"] = bodyLatestError
				}
				if bodyPrefix != "" {
					bodyMap["prefix"] = bodyPrefix
				}
				{
					nestedRevenueAnalyticsConfig := map[string]any{}
					if cmd.Flags().Changed("revenue-analytics-config-enabled") {
						nestedRevenueAnalyticsConfig["enabled"] = bodyRevenueAnalyticsConfigEnabled
					}
					if cmd.Flags().Changed("revenue-analytics-config-include-invoiceless-charges") {
						nestedRevenueAnalyticsConfig["include_invoiceless_charges"] = bodyRevenueAnalyticsConfigIncludeInvoicelessCharges
					}
					if len(nestedRevenueAnalyticsConfig) > 0 {
						bodyMap["revenue_analytics_config"] = nestedRevenueAnalyticsConfig
					}
				}
				if bodySchemas != "" {
					var parsedSchemas any
					if err := json.Unmarshal([]byte(bodySchemas), &parsedSchemas); err != nil {
						return fmt.Errorf("parsing --schemas JSON: %w", err)
					}
					asArray, ok := parsedSchemas.([]any)
					if !ok {
						return fmt.Errorf("--schemas must be a JSON array, got JSON %T", parsedSchemas)
					}
					bodyMap["schemas"] = asArray
				}
				if bodySourceType != "" {
					bodyMap["source_type"] = bodySourceType
				}
				if bodyStatus != "" {
					bodyMap["status"] = bodyStatus
				}
				if bodySupportsColumnSelection != "" {
					parsedSupportsColumnSelection, err := strconv.ParseBool(bodySupportsColumnSelection)
					if err != nil {
						return fmt.Errorf("parsing --supports-column-selection as bool: %w", err)
					}
					bodyMap["supports_column_selection"] = parsedSupportsColumnSelection
				}
				if bodySupportsWebhooks != "" {
					parsedSupportsWebhooks, err := strconv.ParseBool(bodySupportsWebhooks)
					if err != nil {
						return fmt.Errorf("parsing --supports-webhooks as bool: %w", err)
					}
					bodyMap["supports_webhooks"] = parsedSupportsWebhooks
				}
				if bodyUserAccessLevel != "" {
					bodyMap["user_access_level"] = bodyUserAccessLevel
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "delete-webhook", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "delete-webhook", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "delete-webhook", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "delete-webhook", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "delete-webhook", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "delete-webhook",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "delete-webhook", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "delete-webhook", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAccessMethod, "access-method", "", "* `warehouse` - warehouse * `direct` - direct")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "Account id")
	cmd.Flags().StringVar(&bodyApiVersion, "api-version", "", "Vendor API version this source is pinned to (an opaque vendor label, e.g. a Stripe date version).")
	cmd.Flags().StringVar(&bodyApiVersionDeprecation, "api-version-deprecation", "", "Set when the vendor has deprecated the API version this source is pinned to; null otherwise.")
	cmd.Flags().BoolVar(&bodyAutoSyncNewSchemas, "auto-sync-new-schemas", false, "Automatically enable syncing for schemas discovered on this source after creation")
	cmd.Flags().StringVar(&bodyAutoSyncSchemaPatterns, "auto-sync-schema-patterns", "", "Optional fnmatch-style globs (`*` and `?")
	cmd.Flags().StringVar(&bodyClientSecret, "client-secret", "", "Client secret")
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyCreatedBy, "created-by", "", "Created by")
	cmd.Flags().StringVar(&bodyCreatedVia, "created-via", "", "How this source was created. Defaults to `api` on create when omitted.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().BoolVar(&bodyDirectQueryEnabled, "direct-query-enabled", false, "Whether this synced source is also live-queryable via direct connection.")
	cmd.Flags().StringVar(&bodyEngine, "engine", "", "Backend engine detected for the direct connection.")
	cmd.Flags().StringVar(&bodyId2, "id-2", "", "Id")
	cmd.Flags().StringVar(&bodyJobInputs, "job-inputs", "", "Job inputs")
	cmd.Flags().StringVar(&bodyLastRunAt, "last-run-at", "", "Last run at")
	cmd.Flags().StringVar(&bodyLatestError, "latest-error", "", "Latest error")
	cmd.Flags().StringVar(&bodyPrefix, "prefix", "", "Prefix")
	cmd.Flags().BoolVar(&bodyRevenueAnalyticsConfigEnabled, "revenue-analytics-config-enabled", false, "Enabled")
	cmd.Flags().BoolVar(&bodyRevenueAnalyticsConfigIncludeInvoicelessCharges, "revenue-analytics-config-include-invoiceless-charges", false, "Include invoiceless charges")
	cmd.Flags().StringVar(&bodySchemas, "schemas", "", "Schemas")
	cmd.Flags().StringVar(&bodySourceType, "source-type", "", "* `Ashby` - Ashby * `Supabase` - Supabase * `CustomerIO` - CustomerIO * `Github` - Github * `Stripe` - Stripe *")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Status")
	cmd.Flags().StringVar(&bodySupportsColumnSelection, "supports-column-selection", "", "Whether this source supports per-column sync selection via `enabled_columns`.")
	cmd.Flags().StringVar(&bodySupportsWebhooks, "supports-webhooks", "", "Supports webhooks")
	cmd.Flags().StringVar(&bodyUserAccessLevel, "user-access-level", "", "The effective access level the user has for this object")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
