// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExternalDataSchemasCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "external-data-schemas",
		Short:       "Manage external data schemas",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExternalDataSchemasDestroyCmd(flags))
	cmd.AddCommand(newExternalDataSchemasListCmd(flags))
	cmd.AddCommand(newExternalDataSchemasPartialUpdateCmd(flags))
	cmd.AddCommand(newExternalDataSchemasRetrieveCmd(flags))
	cmd.AddCommand(newExternalDataSchemasUpdateCmd(flags))
	cmd.AddCommand(newExternalDataSchemasCancelCmd(flags))
	cmd.AddCommand(newExternalDataSchemasDeleteDataCmd(flags))
	cmd.AddCommand(newExternalDataSchemasIncrementalFieldsCmd(flags))
	cmd.AddCommand(newExternalDataSchemasLogsCmd(flags))
	cmd.AddCommand(newExternalDataSchemasReloadCmd(flags))
	cmd.AddCommand(newExternalDataSchemasResyncCmd(flags))
	return cmd
}
