// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFileSystemCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "file-system",
		Short:       "List, get, count, create, update, and delete file system",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFileSystemCountByPathCreateCmd(flags))
	cmd.AddCommand(newFileSystemCreateCmd(flags))
	cmd.AddCommand(newFileSystemDestroyCmd(flags))
	cmd.AddCommand(newFileSystemListCmd(flags))
	cmd.AddCommand(newFileSystemLogViewCreateCmd(flags))
	cmd.AddCommand(newFileSystemLogViewRetrieveCmd(flags))
	cmd.AddCommand(newFileSystemPartialUpdateCmd(flags))
	cmd.AddCommand(newFileSystemRetrieveCmd(flags))
	cmd.AddCommand(newFileSystemUndoDeleteCreateCmd(flags))
	cmd.AddCommand(newFileSystemUnfiledRetrieveCmd(flags))
	cmd.AddCommand(newFileSystemUpdateCmd(flags))
	cmd.AddCommand(newFileSystemCountCmd(flags))
	cmd.AddCommand(newFileSystemLinkCmd(flags))
	cmd.AddCommand(newFileSystemMoveCmd(flags))
	return cmd
}
