// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFileSystemShortcutCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "file-system-shortcut",
		Short:       "Manage file system shortcut",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFileSystemShortcutCreateCmd(flags))
	cmd.AddCommand(newFileSystemShortcutDestroyCmd(flags))
	cmd.AddCommand(newFileSystemShortcutListCmd(flags))
	cmd.AddCommand(newFileSystemShortcutPartialUpdateCmd(flags))
	cmd.AddCommand(newFileSystemShortcutReorderCreateCmd(flags))
	cmd.AddCommand(newFileSystemShortcutRetrieveCmd(flags))
	cmd.AddCommand(newFileSystemShortcutUpdateCmd(flags))
	return cmd
}
