// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsTypesMetricsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "metrics",
		Short:       "Get, create, update, and delete metrics for groups types",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesCreateCmd(flags))
	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesDestroyCmd(flags))
	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesListCmd(flags))
	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesPartialUpdateCmd(flags))
	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesRetrieveCmd(flags))
	cmd.AddCommand(newGroupsTypesMetricsGroupsTypesUpdateCmd(flags))
	return cmd
}
