// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newHogFunctionsMetricsHogFunctionsRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagAfter string
	var flagBefore string
	var flagBreakdownBy string
	var flagInstanceId string
	var flagInterval string
	var flagKind string
	var flagName string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "hog-functions-retrieve <project_id> <id>",
		Aliases:     []string{"get"},
		Short:       "Hog functions retrieve",
		Example:     "  posthog-pp-cli hog-functions metrics hog-functions-retrieve 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "metrics.hog-functions-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/hog_functions/{id}/metrics/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <id>"))
			}
			if cmd.Flags().Changed("breakdown-by") {
				allowedBreakdownBy := []string{"name", "kind"}
				validBreakdownBy := false
				for _, v := range allowedBreakdownBy {
					if flagBreakdownBy == v {
						validBreakdownBy = true
						break
					}
				}
				if !validBreakdownBy {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagBreakdownBy, "breakdown-by", allowedBreakdownBy)
				}
			}
			if cmd.Flags().Changed("interval") {
				allowedInterval := []string{"hour", "day", "week"}
				validInterval := false
				for _, v := range allowedInterval {
					if flagInterval == v {
						validInterval = true
						break
					}
				}
				if !validInterval {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagInterval, "interval", allowedInterval)
				}
			}
			path := "/api/projects/{project_id}/hog_functions/{id}/metrics/"
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "metrics", path, map[string]string{
				"after":        formatCLIParamValue(flagAfter),
				"before":       formatCLIParamValue(flagBefore),
				"breakdown_by": formatCLIParamValue(flagBreakdownBy),
				"instance_id":  formatCLIParamValue(flagInstanceId),
				"interval":     formatCLIParamValue(flagInterval),
				"kind":         formatCLIParamValue(flagKind),
				"name":         formatCLIParamValue(flagName),
			}, nil, flagAll, "after", "cursor", "", 100, "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagAfter, "after", "-7d", "Start of the time range. Accepts relative formats like '-7d', '-24h' or ISO 8601 timestamps. Defaults to '-7d'.")
	cmd.Flags().StringVar(&flagBefore, "before", "", "End of the time range. Same format as 'after'. Defaults to now.")
	cmd.Flags().StringVar(&flagBreakdownBy, "breakdown-by", "kind", "Group the series by metric 'name' or 'kind'. Defaults to 'kind'. * `name` - name * `kind` - kind (one of: name, kind)")
	cmd.Flags().StringVar(&flagInstanceId, "instance-id", "", "Filter metrics to a specific execution instance.")
	cmd.Flags().StringVar(&flagInterval, "interval", "day", "Time bucket size for the series. One of: hour, day, week. Defaults to 'day'. (one of: hour, day, week)")
	cmd.Flags().StringVar(&flagKind, "kind", "", "Comma-separated metric kinds to filter by, e.g. 'success,failure'.")
	cmd.Flags().StringVar(&flagName, "name", "", "Comma-separated metric names to filter by.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
