// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInsightsSharingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sharing",
		Short:       "Get, create, and delete sharing for insights",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInsightsSharingInsightsListCmd(flags))
	cmd.AddCommand(newInsightsSharingInsightsPasswordsCreateCmd(flags))
	cmd.AddCommand(newInsightsSharingInsightsPasswordsDestroyCmd(flags))
	cmd.AddCommand(newInsightsSharingInsightsRefreshCreateCmd(flags))
	return cmd
}
