// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLiveDebuggerBreakpointsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "live-debugger-breakpoints",
		Short:       "Manage live debugger breakpoints",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLiveDebuggerBreakpointsActiveRetrieveCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsBreakpointHitsRetrieveCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsCreateCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsDestroyCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsListCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsPartialUpdateCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsRetrieveCmd(flags))
	cmd.AddCommand(newLiveDebuggerBreakpointsUpdateCmd(flags))
	return cmd
}
