// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLlmSkillsNameExportRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagVersion int

	cmd := &cobra.Command{
		Use:         "name-export-retrieve <project_id> <skill_name>",
		Short:       "Name export retrieve",
		Example:     "  posthog-pp-cli llm-skills name-export-retrieve 550e8400-e29b-41d4-a716-446655440000 example-resource",
		Annotations: map[string]string{"pp:endpoint": "llm-skills.name-export-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/llm_skills/name/{skill_name}/export/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <skill_name>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <skill_name>"))
			}
			path := "/api/projects/{project_id}/llm_skills/name/{skill_name}/export/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("skill_name is required\nUsage: %s <%s>", cmd.CommandPath(), "skill_name"))
			}
			path = replacePathParam(path, "skill_name", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{
				"Accept":                           "application/zip",
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			if flagVersion != 0 {
				params["version"] = formatCLIParamValue(flagVersion)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "llm-skills", false, path, params, headerOverrides, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().IntVar(&flagVersion, "version", 0, "Specific skill version to fetch. If omitted, the latest version is returned.")

	return cmd
}
