// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newLlmSkillsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAllowedTools string
	var bodyBody string
	var bodyBodyNextOffset int
	var bodyBodyTotalLength int
	var bodyCategory string
	var bodyCompatibility string
	var bodyCreatedAt string
	var bodyCreatedByDistinctId string
	var bodyCreatedByEmail string
	var bodyCreatedByFirstName string
	var bodyCreatedByHedgehogConfig string
	var bodyCreatedById string
	var bodyCreatedByIsEmailVerified bool
	var bodyCreatedByLastName string
	var bodyCreatedByRoleAtOrganization string
	var bodyCreatedByUuid string
	var bodyDeleted string
	var bodyDescription string
	var bodyFiles string
	var bodyFirstVersionCreatedAt string
	var bodyId string
	var bodyIsLatest string
	var bodyLatestVersion int
	var bodyLicense string
	var bodyMetadata string
	var bodyName string
	var bodyOutline string
	var bodyOwners string
	var bodyUpdatedAt string
	var bodyVersion int
	var bodyVersionCount int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create <project_id>",
		Short: "Create",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  posthog-pp-cli llm-skills create 550e8400-e29b-41d4-a716-446655440000 --body example-value",
		Annotations: map[string]string{"pp:endpoint": "llm-skills.create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/llm_skills/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("body") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body")
				}
				if !cmd.Flags().Changed("body-next-offset") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-next-offset")
				}
				if !cmd.Flags().Changed("body-total-length") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-total-length")
				}
				if !cmd.Flags().Changed("category") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "category")
				}
				if !cmd.Flags().Changed("created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-at")
				}
				if !cmd.Flags().Changed("created-by-email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-email")
				}
				if !cmd.Flags().Changed("created-by-hedgehog-config") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-hedgehog-config")
				}
				if !cmd.Flags().Changed("created-by-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-id")
				}
				if !cmd.Flags().Changed("created-by-uuid") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-uuid")
				}
				if !cmd.Flags().Changed("deleted") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "deleted")
				}
				if !cmd.Flags().Changed("description") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "description")
				}
				if !cmd.Flags().Changed("first-version-created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "first-version-created-at")
				}
				if !cmd.Flags().Changed("id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "id")
				}
				if !cmd.Flags().Changed("is-latest") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "is-latest")
				}
				if !cmd.Flags().Changed("latest-version") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "latest-version")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("outline") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "outline")
				}
				if !cmd.Flags().Changed("updated-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "updated-at")
				}
				if !cmd.Flags().Changed("version") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "version")
				}
				if !cmd.Flags().Changed("version-count") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "version-count")
				}
			}
			path := "/api/projects/{project_id}/llm_skills/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("allowed-tools") {
					parsedAllowedTools, parseErr := cliutil.ParseStringList(bodyAllowedTools)
					if parseErr != nil {
						return fmt.Errorf("parsing --allowed-tools list: %w", parseErr)
					}
					bodyMap["allowed_tools"] = parsedAllowedTools
				}
				if bodyBody != "" {
					bodyMap["body"] = bodyBody
				}
				if bodyBodyNextOffset != 0 {
					bodyMap["body_next_offset"] = bodyBodyNextOffset
				}
				if bodyBodyTotalLength != 0 {
					bodyMap["body_total_length"] = bodyBodyTotalLength
				}
				if bodyCategory != "" {
					bodyMap["category"] = bodyCategory
				}
				if bodyCompatibility != "" {
					bodyMap["compatibility"] = bodyCompatibility
				}
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				{
					nestedCreatedBy := map[string]any{}
					if bodyCreatedByDistinctId != "" {
						nestedCreatedBy["distinct_id"] = bodyCreatedByDistinctId
					}
					if bodyCreatedByEmail != "" {
						nestedCreatedBy["email"] = bodyCreatedByEmail
					}
					if bodyCreatedByFirstName != "" {
						nestedCreatedBy["first_name"] = bodyCreatedByFirstName
					}
					if bodyCreatedByHedgehogConfig != "" {
						var parsedCreatedByHedgehogConfig any
						if err := json.Unmarshal([]byte(bodyCreatedByHedgehogConfig), &parsedCreatedByHedgehogConfig); err != nil {
							return fmt.Errorf("parsing --created-by-hedgehog-config JSON: %w", err)
						}
						asMap, ok := parsedCreatedByHedgehogConfig.(map[string]any)
						if !ok {
							return fmt.Errorf("--created-by-hedgehog-config must be a JSON object, got JSON %T", parsedCreatedByHedgehogConfig)
						}
						nestedCreatedBy["hedgehog_config"] = asMap
					}
					if bodyCreatedById != "" {
						nestedCreatedBy["id"] = bodyCreatedById
					}
					if cmd.Flags().Changed("created-by-is-email-verified") {
						nestedCreatedBy["is_email_verified"] = bodyCreatedByIsEmailVerified
					}
					if bodyCreatedByLastName != "" {
						nestedCreatedBy["last_name"] = bodyCreatedByLastName
					}
					if bodyCreatedByRoleAtOrganization != "" {
						nestedCreatedBy["role_at_organization"] = bodyCreatedByRoleAtOrganization
					}
					if bodyCreatedByUuid != "" {
						nestedCreatedBy["uuid"] = bodyCreatedByUuid
					}
					if len(nestedCreatedBy) > 0 {
						bodyMap["created_by"] = nestedCreatedBy
					}
				}
				if bodyDeleted != "" {
					parsedDeleted, err := strconv.ParseBool(bodyDeleted)
					if err != nil {
						return fmt.Errorf("parsing --deleted as bool: %w", err)
					}
					bodyMap["deleted"] = parsedDeleted
				}
				if bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if bodyFiles != "" {
					var parsedFiles any
					if err := json.Unmarshal([]byte(bodyFiles), &parsedFiles); err != nil {
						return fmt.Errorf("parsing --files JSON: %w", err)
					}
					asArray, ok := parsedFiles.([]any)
					if !ok {
						return fmt.Errorf("--files must be a JSON array, got JSON %T", parsedFiles)
					}
					bodyMap["files"] = asArray
				}
				if bodyFirstVersionCreatedAt != "" {
					bodyMap["first_version_created_at"] = bodyFirstVersionCreatedAt
				}
				if bodyId != "" {
					bodyMap["id"] = bodyId
				}
				if bodyIsLatest != "" {
					parsedIsLatest, err := strconv.ParseBool(bodyIsLatest)
					if err != nil {
						return fmt.Errorf("parsing --is-latest as bool: %w", err)
					}
					bodyMap["is_latest"] = parsedIsLatest
				}
				if bodyLatestVersion != 0 {
					bodyMap["latest_version"] = bodyLatestVersion
				}
				if bodyLicense != "" {
					bodyMap["license"] = bodyLicense
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					asMap, ok := parsedMetadata.(map[string]any)
					if !ok {
						return fmt.Errorf("--metadata must be a JSON object, got JSON %T", parsedMetadata)
					}
					bodyMap["metadata"] = asMap
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if bodyOutline != "" {
					var parsedOutline any
					if err := json.Unmarshal([]byte(bodyOutline), &parsedOutline); err != nil {
						return fmt.Errorf("parsing --outline JSON: %w", err)
					}
					asArray, ok := parsedOutline.([]any)
					if !ok {
						return fmt.Errorf("--outline must be a JSON array, got JSON %T", parsedOutline)
					}
					bodyMap["outline"] = asArray
				}
				if cmd.Flags().Changed("owners") {
					parsedOwners, parseErr := cliutil.ParseStringList(bodyOwners)
					if parseErr != nil {
						return fmt.Errorf("parsing --owners list: %w", parseErr)
					}
					bodyMap["owners"] = parsedOwners
				}
				if bodyUpdatedAt != "" {
					bodyMap["updated_at"] = bodyUpdatedAt
				}
				if bodyVersion != 0 {
					bodyMap["version"] = bodyVersion
				}
				if bodyVersionCount != 0 {
					bodyMap["version_count"] = bodyVersionCount
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "llm-skills", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "llm-skills", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-skills", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-skills", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-skills", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "llm-skills",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-skills", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-skills", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAllowedTools, "allowed-tools", "", "List of pre-approved tools the skill may use. Tool names cannot contain whitespace.")
	cmd.Flags().StringVar(&bodyBody, "body", "", "The SKILL.md instruction content (markdown).")
	cmd.Flags().IntVar(&bodyBodyNextOffset, "body-next-offset", 0, "When body_length paging stops before the end of the body, the character offset to request next (pass as body_offset).")
	cmd.Flags().IntVar(&bodyBodyTotalLength, "body-total-length", 0, "Total length of the full body in characters, independent of any body_offset/body_length paging.")
	cmd.Flags().StringVar(&bodyCategory, "category", "", "Server-owned classification — set by the producing system (the Signals harness stamps 'scout')")
	cmd.Flags().StringVar(&bodyCompatibility, "compatibility", "", "Environment requirements (intended product, system packages, network access, etc.).")
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyCreatedByDistinctId, "created-by-distinct-id", "", "Distinct id")
	cmd.Flags().StringVar(&bodyCreatedByEmail, "created-by-email", "", "Email")
	cmd.Flags().StringVar(&bodyCreatedByFirstName, "created-by-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyCreatedByHedgehogConfig, "created-by-hedgehog-config", "", "Hedgehog config")
	cmd.Flags().StringVar(&bodyCreatedById, "created-by-id", "", "Id")
	cmd.Flags().BoolVar(&bodyCreatedByIsEmailVerified, "created-by-is-email-verified", false, "Is email verified")
	cmd.Flags().StringVar(&bodyCreatedByLastName, "created-by-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyCreatedByRoleAtOrganization, "created-by-role-at-organization", "", "Role at organization")
	cmd.Flags().StringVar(&bodyCreatedByUuid, "created-by-uuid", "", "Uuid")
	cmd.Flags().StringVar(&bodyDeleted, "deleted", "", "Deleted")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "What this skill does and when to use it. Max 4096 characters.")
	cmd.Flags().StringVar(&bodyFiles, "files", "", "Bundled files to include with the initial version (scripts, references, assets).")
	cmd.Flags().StringVar(&bodyFirstVersionCreatedAt, "first-version-created-at", "", "First version created at")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().StringVar(&bodyIsLatest, "is-latest", "", "Is latest")
	cmd.Flags().IntVar(&bodyLatestVersion, "latest-version", 0, "Latest version")
	cmd.Flags().StringVar(&bodyLicense, "license", "", "License name or reference to a bundled license file.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Arbitrary key-value metadata.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Unique skill name. Lowercase letters, numbers, and hyphens only. Max 64 characters.")
	cmd.Flags().StringVar(&bodyOutline, "outline", "", "Flat list of markdown headings parsed from the skill body. Useful as a lightweight table of contents.")
	cmd.Flags().StringVar(&bodyOwners, "owners", "", "User UUIDs to set as the skill's owners. Each must be a member of this project.")
	cmd.Flags().StringVar(&bodyUpdatedAt, "updated-at", "", "Updated at")
	cmd.Flags().IntVar(&bodyVersion, "version", 0, "Version")
	cmd.Flags().IntVar(&bodyVersionCount, "version-count", 0, "Version count")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
