// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newLlmAnalyticsClusteringRunsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClusteringJobId string
	var bodyClusteringMethod string
	var bodyDimensionalityReductionMethod string
	var bodyDimensionalityReductionNdims int
	var bodyEmbeddingNormalization string
	var bodyEventFilters string
	var bodyHdbscanMinSamples int
	var bodyKmeansMaxK int
	var bodyKmeansMinK int
	var bodyLookbackDays int
	var bodyMaxSamples int
	var bodyMinClusterSizeFraction float64
	var bodyRunLabel string
	var bodyVisualizationMethod string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "clustering-runs-create <project_id>",
		Short:       "Trigger a new clustering workflow run.",
		Example:     "  posthog-pp-cli llm-analytics clustering-runs-create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "llm-analytics.clustering-runs-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/llm_analytics/clustering_runs/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
			}
			path := "/api/projects/{project_id}/llm_analytics/clustering_runs/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyClusteringJobId != "" {
					bodyMap["clustering_job_id"] = bodyClusteringJobId
				}
				if bodyClusteringMethod != "" {
					bodyMap["clustering_method"] = bodyClusteringMethod
				}
				if bodyDimensionalityReductionMethod != "" {
					bodyMap["dimensionality_reduction_method"] = bodyDimensionalityReductionMethod
				}
				if bodyDimensionalityReductionNdims != 0 {
					bodyMap["dimensionality_reduction_ndims"] = bodyDimensionalityReductionNdims
				}
				if bodyEmbeddingNormalization != "" {
					bodyMap["embedding_normalization"] = bodyEmbeddingNormalization
				}
				if bodyEventFilters != "" {
					var parsedEventFilters any
					if err := json.Unmarshal([]byte(bodyEventFilters), &parsedEventFilters); err != nil {
						return fmt.Errorf("parsing --event-filters JSON: %w", err)
					}
					asArray, ok := parsedEventFilters.([]any)
					if !ok {
						return fmt.Errorf("--event-filters must be a JSON array, got JSON %T", parsedEventFilters)
					}
					bodyMap["event_filters"] = asArray
				}
				if bodyHdbscanMinSamples != 0 {
					bodyMap["hdbscan_min_samples"] = bodyHdbscanMinSamples
				}
				if bodyKmeansMaxK != 0 {
					bodyMap["kmeans_max_k"] = bodyKmeansMaxK
				}
				if bodyKmeansMinK != 0 {
					bodyMap["kmeans_min_k"] = bodyKmeansMinK
				}
				if bodyLookbackDays != 0 {
					bodyMap["lookback_days"] = bodyLookbackDays
				}
				if bodyMaxSamples != 0 {
					bodyMap["max_samples"] = bodyMaxSamples
				}
				if bodyMinClusterSizeFraction != 0.0 {
					bodyMap["min_cluster_size_fraction"] = bodyMinClusterSizeFraction
				}
				if bodyRunLabel != "" {
					bodyMap["run_label"] = bodyRunLabel
				}
				if bodyVisualizationMethod != "" {
					bodyMap["visualization_method"] = bodyVisualizationMethod
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "llm-analytics", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "llm-analytics", data, "event_filters")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-analytics", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-analytics", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-analytics", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "llm-analytics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-analytics", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "llm-analytics", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyClusteringJobId, "clustering-job-id", "", "If provided, use this clustering job's analysis_level and event_filters instead of request params")
	cmd.Flags().StringVar(&bodyClusteringMethod, "clustering-method", "", "Clustering algorithm: 'hdbscan' (density-based, auto-determines k) or 'kmeans' (centroid-based)")
	cmd.Flags().StringVar(&bodyDimensionalityReductionMethod, "dimensionality-reduction-method", "", "Dimensionality reduction method: 'none' (cluster on raw), 'umap', or 'pca' * `none` - none * `umap` - umap * `pca` - pca")
	cmd.Flags().IntVar(&bodyDimensionalityReductionNdims, "dimensionality-reduction-ndims", 100, "Target dimensions for dimensionality reduction (ignored if method is 'none')")
	cmd.Flags().StringVar(&bodyEmbeddingNormalization, "embedding-normalization", "", "Embedding normalization method: 'none' (raw embeddings) or 'l2' (L2 normalize before clustering)")
	cmd.Flags().StringVar(&bodyEventFilters, "event-filters", "", "Property filters to scope which traces are included in clustering (PostHog standard format)")
	cmd.Flags().IntVar(&bodyHdbscanMinSamples, "hdbscan-min-samples", 5, "HDBSCAN min_samples parameter (higher = more conservative clustering)")
	cmd.Flags().IntVar(&bodyKmeansMaxK, "kmeans-max-k", 20, "Maximum number of clusters to try for k-means")
	cmd.Flags().IntVar(&bodyKmeansMinK, "kmeans-min-k", 2, "Minimum number of clusters to try for k-means")
	cmd.Flags().IntVar(&bodyLookbackDays, "lookback-days", 7, "Number of days to look back for traces")
	cmd.Flags().IntVar(&bodyMaxSamples, "max-samples", 1500, "Maximum number of traces to sample for clustering")
	cmd.Flags().Float64Var(&bodyMinClusterSizeFraction, "min-cluster-size-fraction", 0.020000, "Minimum cluster size as fraction of total samples (e.g., 0.02 = 2%)")
	cmd.Flags().StringVar(&bodyRunLabel, "run-label", "", "Optional label/tag for the clustering run (used as suffix in run_id for tracking experiments)")
	cmd.Flags().StringVar(&bodyVisualizationMethod, "visualization-method", "", "Method for 2D scatter plot visualization: 'umap', 'pca', or 'tsne' * `umap` - umap * `pca` - pca * `tsne` - tsne")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
