// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLlmPromptsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "llm-prompts",
		Short:       "List, get, create, update, and delete llm prompts",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLlmPromptsCreateCmd(flags))
	cmd.AddCommand(newLlmPromptsListCmd(flags))
	cmd.AddCommand(newLlmPromptsNameArchiveCreateCmd(flags))
	cmd.AddCommand(newLlmPromptsNameDuplicateCreateCmd(flags))
	cmd.AddCommand(newLlmPromptsNameLabelsDestroyCmd(flags))
	cmd.AddCommand(newLlmPromptsNameLabelsUpdateCmd(flags))
	cmd.AddCommand(newLlmPromptsNamePartialUpdateCmd(flags))
	cmd.AddCommand(newLlmPromptsNameRetrieveCmd(flags))
	cmd.AddCommand(newLlmPromptsResolveNameRetrieveCmd(flags))
	return cmd
}
