// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMcpServerInstallationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "mcp-server-installations",
		Short:       "Manage mcp server installations",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMcpServerInstallationsAuthorizeRetrieveCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsAvailableToolsRetrieveCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsCreateCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsDestroyCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsInstallCustomCreateCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsInstallTemplateCreateCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsListCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsPartialUpdateCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsRetrieveCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsUpdateCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsCallToolCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsProxyCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsShareCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsToolsCmd(flags))
	cmd.AddCommand(newMcpServerInstallationsUnshareCmd(flags))
	return cmd
}
