// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newMetricsQueryCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyQueryAggregation string
	var bodyQueryClauses string
	var bodyQueryDateFrom string
	var bodyQueryDateTo string
	var bodyQueryFilters string
	var bodyQueryFormula string
	var bodyQueryGroupBy string
	var bodyQueryInterval string
	var bodyQueryMetricName string
	var bodyQueryMetricType string
	var bodyQueryQuantile float64
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "query-create <project_id>",
		Short:       "Query create",
		Example:     "  posthog-pp-cli metrics query-create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "metrics.query-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/metrics/query/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("query-date-from") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "query-date-from")
				}
			}
			path := "/api/projects/{project_id}/metrics/query/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedQuery := map[string]any{}
					if bodyQueryAggregation != "" {
						nestedQuery["aggregation"] = bodyQueryAggregation
					}
					if bodyQueryClauses != "" {
						var parsedQueryClauses any
						if err := json.Unmarshal([]byte(bodyQueryClauses), &parsedQueryClauses); err != nil {
							return fmt.Errorf("parsing --query-clauses JSON: %w", err)
						}
						asArray, ok := parsedQueryClauses.([]any)
						if !ok {
							return fmt.Errorf("--query-clauses must be a JSON array, got JSON %T", parsedQueryClauses)
						}
						nestedQuery["clauses"] = asArray
					}
					if bodyQueryDateFrom != "" {
						nestedQuery["dateFrom"] = bodyQueryDateFrom
					}
					if bodyQueryDateTo != "" {
						nestedQuery["dateTo"] = bodyQueryDateTo
					}
					if bodyQueryFilters != "" {
						var parsedQueryFilters any
						if err := json.Unmarshal([]byte(bodyQueryFilters), &parsedQueryFilters); err != nil {
							return fmt.Errorf("parsing --query-filters JSON: %w", err)
						}
						asArray, ok := parsedQueryFilters.([]any)
						if !ok {
							return fmt.Errorf("--query-filters must be a JSON array, got JSON %T", parsedQueryFilters)
						}
						nestedQuery["filters"] = asArray
					}
					if bodyQueryFormula != "" {
						nestedQuery["formula"] = bodyQueryFormula
					}
					if bodyQueryGroupBy != "" {
						var parsedQueryGroupBy any
						if err := json.Unmarshal([]byte(bodyQueryGroupBy), &parsedQueryGroupBy); err != nil {
							return fmt.Errorf("parsing --query-group-by JSON: %w", err)
						}
						asArray, ok := parsedQueryGroupBy.([]any)
						if !ok {
							return fmt.Errorf("--query-group-by must be a JSON array, got JSON %T", parsedQueryGroupBy)
						}
						nestedQuery["groupBy"] = asArray
					}
					if bodyQueryInterval != "" {
						nestedQuery["interval"] = bodyQueryInterval
					}
					if bodyQueryMetricName != "" {
						nestedQuery["metricName"] = bodyQueryMetricName
					}
					if bodyQueryMetricType != "" {
						nestedQuery["metricType"] = bodyQueryMetricType
					}
					if bodyQueryQuantile != 0.0 {
						nestedQuery["quantile"] = bodyQueryQuantile
					}
					if len(nestedQuery) > 0 {
						bodyMap["query"] = nestedQuery
					}
				}
			}
			data, statusCode, err := c.PostQueryWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "metrics", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "metrics", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "metrics", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "metrics", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "metrics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "metrics", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "metrics", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyQueryAggregation, "query-aggregation", "", "Aggregation applied per time bucket.")
	cmd.Flags().StringVar(&bodyQueryClauses, "query-clauses", "", "Full multi-clause form: each clause is an independent metric selection sharing the request's time grid (maximum 10).")
	cmd.Flags().StringVar(&bodyQueryDateFrom, "query-date-from", "", "Lower bound (inclusive) for the query range. ISO 8601.")
	cmd.Flags().StringVar(&bodyQueryDateTo, "query-date-to", "", "Upper bound (exclusive) for the query range. Defaults to now if omitted.")
	cmd.Flags().StringVar(&bodyQueryFilters, "query-filters", "", "Label predicates ANDed together. Rows must satisfy every filter.")
	cmd.Flags().StringVar(&bodyQueryFormula, "query-formula", "", "Arithmetic over clause names evaluated server-side per grid point, e.g. '(a - b) / a'.")
	cmd.Flags().StringVar(&bodyQueryGroupBy, "query-group-by", "", "Labels to split the result into separate series by. Series share one time grid and are capped at the 100 largest.")
	cmd.Flags().StringVar(&bodyQueryInterval, "query-interval", "", "Bucket size for the shared time grid. Omit to auto-pick (~60 buckets across the range).")
	cmd.Flags().StringVar(&bodyQueryMetricName, "query-metric-name", "", "Exact metric name to query (e.g. 'http.server.duration'). Single-clause shorthand — mutually exclusive with 'clauses'.")
	cmd.Flags().StringVar(&bodyQueryMetricType, "query-metric-type", "", "Constrain the query to one metric type. A name can exist as several types (e.g.")
	cmd.Flags().Float64Var(&bodyQueryQuantile, "query-quantile", 0.0, "Quantile in (0, 1) for 'histogram_quantile' (e.g. 0.95). Ignored for other aggregations.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
