// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsBatchExportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "batch-exports",
		Short:       "Get, create, update, and delete batch exports for organizations",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsCreateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsDestroyCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsListCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsLogsRetrieveCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsPartialUpdateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsPauseCreateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsRetrieveCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsRunTestStepCreateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsRunTestStepNewCreateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsTestRetrieveCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsUnpauseCreateCmd(flags))
	cmd.AddCommand(newOrganizationsBatchExportsOrgOrganizationsUpdateCmd(flags))
	return cmd
}
