// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsRoleExternalReferencesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "role-external-references",
		Short:       "Manage role external references",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationsRoleExternalReferencesCreateCmd(flags))
	cmd.AddCommand(newOrganizationsRoleExternalReferencesDestroyCmd(flags))
	cmd.AddCommand(newOrganizationsRoleExternalReferencesListCmd(flags))
	cmd.AddCommand(newOrganizationsRoleExternalReferencesLookupRetrieveCmd(flags))
	return cmd
}
