// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsPartialUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAllowPubliclySharedResources bool
	var bodyAvailableProductFeatures string
	var bodyCreatedAt string
	var bodyCustomerId string
	var bodyDefaultAnonymizeIps bool
	var bodyDefaultExperimentStatsMethod string
	var bodyDefaultRoleId string
	var bodyEnforce2fa bool
	var bodyEnforceVerifiedDomains bool
	var bodyId2 string
	var bodyIsActive bool
	var bodyIsAiDataProcessingApproved bool
	var bodyIsAiTrainingCtaShown bool
	var bodyIsAiTrainingLocked bool
	var bodyIsAiTrainingOptedIn bool
	var bodyIsHipaa bool
	var bodyIsMemberJoinEmailEnabled bool
	var bodyIsNotActiveReason string
	var bodyIsPendingDeletion bool
	var bodyLogoMediaId string
	var bodyMemberCount int
	var bodyMembersCanCreateProjects bool
	var bodyMembersCanInvite bool
	var bodyMembersCanSeeOrgMembers bool
	var bodyMembersCanUsePersonalApiKeys bool
	var bodyMembershipLevel int
	var bodyMetadata string
	var bodyName string
	var bodyPluginsAccessLevel int
	var bodyProjects string
	var bodySlug string
	var bodyTeams string
	var bodyUpdatedAt string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "partial-update <id>",
		Short:       "Partial update",
		Example:     "  posthog-pp-cli organizations partial-update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "organizations.partial-update", "pp:method": "PATCH", "pp:path": "/api/organizations/{id}/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <id>"))
			}
			if !stdinBody {
			}
			path := "/api/organizations/{id}/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("allow-publicly-shared-resources") {
					bodyMap["allow_publicly_shared_resources"] = bodyAllowPubliclySharedResources
				}
				if bodyAvailableProductFeatures != "" {
					var parsedAvailableProductFeatures any
					if err := json.Unmarshal([]byte(bodyAvailableProductFeatures), &parsedAvailableProductFeatures); err != nil {
						return fmt.Errorf("parsing --available-product-features JSON: %w", err)
					}
					asArray, ok := parsedAvailableProductFeatures.([]any)
					if !ok {
						return fmt.Errorf("--available-product-features must be a JSON array, got JSON %T", parsedAvailableProductFeatures)
					}
					bodyMap["available_product_features"] = asArray
				}
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				if bodyCustomerId != "" {
					bodyMap["customer_id"] = bodyCustomerId
				}
				if cmd.Flags().Changed("default-anonymize-ips") {
					bodyMap["default_anonymize_ips"] = bodyDefaultAnonymizeIps
				}
				if bodyDefaultExperimentStatsMethod != "" {
					bodyMap["default_experiment_stats_method"] = bodyDefaultExperimentStatsMethod
				}
				if bodyDefaultRoleId != "" {
					bodyMap["default_role_id"] = bodyDefaultRoleId
				}
				if cmd.Flags().Changed("enforce-2fa") {
					bodyMap["enforce_2fa"] = bodyEnforce2fa
				}
				if cmd.Flags().Changed("enforce-verified-domains") {
					bodyMap["enforce_verified_domains"] = bodyEnforceVerifiedDomains
				}
				if bodyId2 != "" {
					bodyMap["id"] = bodyId2
				}
				if cmd.Flags().Changed("is-active") {
					bodyMap["is_active"] = bodyIsActive
				}
				if cmd.Flags().Changed("is-ai-data-processing-approved") {
					bodyMap["is_ai_data_processing_approved"] = bodyIsAiDataProcessingApproved
				}
				if cmd.Flags().Changed("is-ai-training-cta-shown") {
					bodyMap["is_ai_training_cta_shown"] = bodyIsAiTrainingCtaShown
				}
				if cmd.Flags().Changed("is-ai-training-locked") {
					bodyMap["is_ai_training_locked"] = bodyIsAiTrainingLocked
				}
				if cmd.Flags().Changed("is-ai-training-opted-in") {
					bodyMap["is_ai_training_opted_in"] = bodyIsAiTrainingOptedIn
				}
				if cmd.Flags().Changed("is-hipaa") {
					bodyMap["is_hipaa"] = bodyIsHipaa
				}
				if cmd.Flags().Changed("is-member-join-email-enabled") {
					bodyMap["is_member_join_email_enabled"] = bodyIsMemberJoinEmailEnabled
				}
				if bodyIsNotActiveReason != "" {
					bodyMap["is_not_active_reason"] = bodyIsNotActiveReason
				}
				if cmd.Flags().Changed("is-pending-deletion") {
					bodyMap["is_pending_deletion"] = bodyIsPendingDeletion
				}
				if bodyLogoMediaId != "" {
					bodyMap["logo_media_id"] = bodyLogoMediaId
				}
				if bodyMemberCount != 0 {
					bodyMap["member_count"] = bodyMemberCount
				}
				if cmd.Flags().Changed("members-can-create-projects") {
					bodyMap["members_can_create_projects"] = bodyMembersCanCreateProjects
				}
				if cmd.Flags().Changed("members-can-invite") {
					bodyMap["members_can_invite"] = bodyMembersCanInvite
				}
				if cmd.Flags().Changed("members-can-see-org-members") {
					bodyMap["members_can_see_org_members"] = bodyMembersCanSeeOrgMembers
				}
				if cmd.Flags().Changed("members-can-use-personal-api-keys") {
					bodyMap["members_can_use_personal_api_keys"] = bodyMembersCanUsePersonalApiKeys
				}
				if bodyMembershipLevel != 0 {
					bodyMap["membership_level"] = bodyMembershipLevel
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					asMap, ok := parsedMetadata.(map[string]any)
					if !ok {
						return fmt.Errorf("--metadata must be a JSON object, got JSON %T", parsedMetadata)
					}
					bodyMap["metadata"] = asMap
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if bodyPluginsAccessLevel != 0 {
					bodyMap["plugins_access_level"] = bodyPluginsAccessLevel
				}
				if bodyProjects != "" {
					var parsedProjects any
					if err := json.Unmarshal([]byte(bodyProjects), &parsedProjects); err != nil {
						return fmt.Errorf("parsing --projects JSON: %w", err)
					}
					asArray, ok := parsedProjects.([]any)
					if !ok {
						return fmt.Errorf("--projects must be a JSON array, got JSON %T", parsedProjects)
					}
					bodyMap["projects"] = asArray
				}
				if bodySlug != "" {
					bodyMap["slug"] = bodySlug
				}
				if bodyTeams != "" {
					var parsedTeams any
					if err := json.Unmarshal([]byte(bodyTeams), &parsedTeams); err != nil {
						return fmt.Errorf("parsing --teams JSON: %w", err)
					}
					asArray, ok := parsedTeams.([]any)
					if !ok {
						return fmt.Errorf("--teams must be a JSON array, got JSON %T", parsedTeams)
					}
					bodyMap["teams"] = asArray
				}
				if bodyUpdatedAt != "" {
					bodyMap["updated_at"] = bodyUpdatedAt
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "organizations", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "organizations", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "organizations", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "organizations", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "organizations", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "organizations",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "organizations", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "organizations", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyAllowPubliclySharedResources, "allow-publicly-shared-resources", false, "Allow publicly shared resources")
	cmd.Flags().StringVar(&bodyAvailableProductFeatures, "available-product-features", "", "Available product features")
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyCustomerId, "customer-id", "", "Customer id")
	cmd.Flags().BoolVar(&bodyDefaultAnonymizeIps, "default-anonymize-ips", false, "Default setting for 'Discard client IP data' for new projects in this organization.")
	cmd.Flags().StringVar(&bodyDefaultExperimentStatsMethod, "default-experiment-stats-method", "", "Default statistical method for new experiments in this organization.")
	cmd.Flags().StringVar(&bodyDefaultRoleId, "default-role-id", "", "ID of the role to automatically assign to new members joining the organization")
	cmd.Flags().BoolVar(&bodyEnforce2fa, "enforce-2fa", false, "Enforce 2fa")
	cmd.Flags().BoolVar(&bodyEnforceVerifiedDomains, "enforce-verified-domains", false, "When True, logins, signups, and invites for this organization are restricted to email addresses on its verified domains.")
	cmd.Flags().StringVar(&bodyId2, "id-2", "", "Id")
	cmd.Flags().BoolVar(&bodyIsActive, "is-active", false, "Set this to 'No' to temporarily disable an organization.")
	cmd.Flags().BoolVar(&bodyIsAiDataProcessingApproved, "is-ai-data-processing-approved", false, "Is ai data processing approved")
	cmd.Flags().BoolVar(&bodyIsAiTrainingCtaShown, "is-ai-training-cta-shown", false, "When True, in-app callouts inviting members to enable AI training are shown.")
	cmd.Flags().BoolVar(&bodyIsAiTrainingLocked, "is-ai-training-locked", false, "When True, the AI training opt-out setting cannot be modified through the UI or API.")
	cmd.Flags().BoolVar(&bodyIsAiTrainingOptedIn, "is-ai-training-opted-in", false, "When True, this organization allows its data to be used to train PostHog AI models.")
	cmd.Flags().BoolVar(&bodyIsHipaa, "is-hipaa", false, "Is hipaa")
	cmd.Flags().BoolVar(&bodyIsMemberJoinEmailEnabled, "is-member-join-email-enabled", false, "Legacy field; member-join emails are controlled per user in account notification settings.")
	cmd.Flags().StringVar(&bodyIsNotActiveReason, "is-not-active-reason", "", "(optional) reason for why the organization has been de-activated. This will be displayed to users on the web app.")
	cmd.Flags().BoolVar(&bodyIsPendingDeletion, "is-pending-deletion", false, "Set to True when org deletion has been initiated. Blocks all UI access until the async task completes.")
	cmd.Flags().StringVar(&bodyLogoMediaId, "logo-media-id", "", "Logo media id")
	cmd.Flags().IntVar(&bodyMemberCount, "member-count", 0, "Member count")
	cmd.Flags().BoolVar(&bodyMembersCanCreateProjects, "members-can-create-projects", false, "When True, organization members (below admin) are allowed to create new projects.")
	cmd.Flags().BoolVar(&bodyMembersCanInvite, "members-can-invite", false, "Members can invite")
	cmd.Flags().BoolVar(&bodyMembersCanSeeOrgMembers, "members-can-see-org-members", false, "When False, members (below admin) only see themselves in the members list and only project members in access control.")
	cmd.Flags().BoolVar(&bodyMembersCanUsePersonalApiKeys, "members-can-use-personal-api-keys", false, "Members can use personal api keys")
	cmd.Flags().IntVar(&bodyMembershipLevel, "membership-level", 0, "Membership level")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().IntVar(&bodyPluginsAccessLevel, "plugins-access-level", 0, "* `0` - none * `3` - config * `6` - install * `9` - root")
	cmd.Flags().StringVar(&bodyProjects, "projects", "", "Projects")
	cmd.Flags().StringVar(&bodySlug, "slug", "", "Slug")
	cmd.Flags().StringVar(&bodyTeams, "teams", "", "Teams")
	cmd.Flags().StringVar(&bodyUpdatedAt, "updated-at", "", "Updated at")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
