// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectSecretApiKeysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "project-secret-api-keys",
		Short:       "Manage project secret api keys",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysCreateCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysDestroyCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysListCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysPartialUpdateCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysRetrieveCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysSecretApiKeysUpdateCmd(flags))
	cmd.AddCommand(newProjectSecretApiKeysRollCmd(flags))
	return cmd
}
