// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPathsV2PromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyItems string
	var bodyQuery string

	cmd := &cobra.Command{
		Use:         "paths-v2 <project_id>",
		Short:       "Converts a displayed journeys segment into the funnel query that reproduces its unique-actor count exactly.",
		Long:        "Converts a displayed journeys segment into the funnel query that reproduces its unique-actor count exactly.",
		Example:     "  posthog-pp-cli paths-v2 550e8400-e29b-41d4-a716-446655440000 --query '{}'",
		Annotations: map[string]string{"pp:endpoint": "paths-v2.segment-to-funnel-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/paths_v2/segment_to_funnel/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("items") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "items")
			}
			if !cmd.Flags().Changed("query") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "query")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/projects/{project_id}/paths_v2/segment_to_funnel/"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "project_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "project_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if bodyItems != "" {
				var parsedItems any
				if err := json.Unmarshal([]byte(bodyItems), &parsedItems); err != nil {
					return fmt.Errorf("parsing --items JSON: %w", err)
				}
				asArray, ok := parsedItems.([]any)
				if !ok {
					return fmt.Errorf("--items must be a JSON array, got JSON %T", parsedItems)
				}
				bodyMap["items"] = asArray
			}
			if bodyQuery != "" {
				var parsedQuery any
				if err := json.Unmarshal([]byte(bodyQuery), &parsedQuery); err != nil {
					return fmt.Errorf("parsing --query JSON: %w", err)
				}
				bodyMap["query"] = bodyQuery
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "paths-v2", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&bodyItems, "items", "", "The segment's path items in displayed order. In open mode exactly two items - a single edge, source then target.")
	cmd.Flags().StringVar(&bodyQuery, "query", "", "The PathsV2Query the segment is displayed under (JSON object with kind `PathsV2Query`).")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
