// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newSignalsScoutEmitCmd(flags *rootFlags) *cobra.Command {
	var bodyConfidence float64
	var bodyDedupeKeys string
	var bodyDescription string
	var bodyEvidence string
	var bodyFindingId string
	var bodyHypothesis string
	var bodyMcpTraceId string
	var bodySeverity string
	var bodyTags string
	var bodyTimeRange string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "scout-emit <project_id> <run_id>",
		Short: "Fire `emit_signal` with `source_product = signals_scout`. The `finding_id` is baked into the deterministic `Signal.",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  posthog-pp-cli signals scout-emit 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --description example-value",
		Annotations: map[string]string{"pp:endpoint": "signals.scout-emit", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/signals/scout/runs/{run_id}/emit-signal/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <run_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <run_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("confidence") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "confidence")
				}
				if !cmd.Flags().Changed("description") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "description")
				}
				if !cmd.Flags().Changed("evidence") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "evidence")
				}
			}
			path := "/api/projects/{project_id}/signals/scout/runs/{run_id}/emit-signal/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("run_id is required\nUsage: %s <%s>", cmd.CommandPath(), "run_id"))
			}
			path = replacePathParam(path, "run_id", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyConfidence != 0.0 {
					bodyMap["confidence"] = bodyConfidence
				}
				if cmd.Flags().Changed("dedupe-keys") {
					parsedDedupeKeys, parseErr := cliutil.ParseStringList(bodyDedupeKeys)
					if parseErr != nil {
						return fmt.Errorf("parsing --dedupe-keys list: %w", parseErr)
					}
					bodyMap["dedupe_keys"] = parsedDedupeKeys
				}
				if bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if bodyEvidence != "" {
					var parsedEvidence any
					if err := json.Unmarshal([]byte(bodyEvidence), &parsedEvidence); err != nil {
						return fmt.Errorf("parsing --evidence JSON: %w", err)
					}
					asArray, ok := parsedEvidence.([]any)
					if !ok {
						return fmt.Errorf("--evidence must be a JSON array, got JSON %T", parsedEvidence)
					}
					bodyMap["evidence"] = asArray
				}
				if bodyFindingId != "" {
					bodyMap["finding_id"] = bodyFindingId
				}
				if bodyHypothesis != "" {
					bodyMap["hypothesis"] = bodyHypothesis
				}
				if bodyMcpTraceId != "" {
					bodyMap["mcp_trace_id"] = bodyMcpTraceId
				}
				if bodySeverity != "" {
					bodyMap["severity"] = bodySeverity
				}
				if cmd.Flags().Changed("tags") {
					parsedTags, parseErr := cliutil.ParseStringList(bodyTags)
					if parseErr != nil {
						return fmt.Errorf("parsing --tags list: %w", parseErr)
					}
					bodyMap["tags"] = parsedTags
				}
				if bodyTimeRange != "" {
					if looksLikeJSONComposite(bodyTimeRange) {
						var parsedTimeRange any
						if err := json.Unmarshal([]byte(bodyTimeRange), &parsedTimeRange); err != nil {
							return fmt.Errorf("parsing --time-range JSON: %w", err)
						}
						bodyMap["time_range"] = parsedTimeRange
					} else {
						bodyMap["time_range"] = bodyTimeRange
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "signals", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "signals", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "signals", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "signals", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "signals", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "signals",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "signals", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "signals", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().Float64Var(&bodyConfidence, "confidence", 0.0, "Agent's confidence the finding is real in [0, 1]. Persisted in `extra`.")
	cmd.Flags().StringVar(&bodyDedupeKeys, "dedupe-keys", "", "Optional keys for downstream dedupe (e.g. `error_tracking_issue:<id>`).")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Canonical evidence-bundle prose. Becomes the signal's `description`.")
	cmd.Flags().StringVar(&bodyEvidence, "evidence", "", "Citations supporting the finding. Capped at 20 entries.")
	cmd.Flags().StringVar(&bodyFindingId, "finding-id", "", "Stable id for this finding, baked into the signal's source_id for traceability.")
	cmd.Flags().StringVar(&bodyHypothesis, "hypothesis", "", "Optional one-line hypothesis the finding tests.")
	cmd.Flags().StringVar(&bodyMcpTraceId, "mcp-trace-id", "", "Optional MCP trace id for cross-system debugging.")
	cmd.Flags().StringVar(&bodySeverity, "severity", "", "Optional severity tag — one of P0, P1, P2, P3, P4. Informational only.")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Optional category tags as lowercase kebab-case slugs (e.g. `cost-spike`, `silent-failure`), max 10.")
	cmd.Flags().StringVar(&bodyTimeRange, "time-range", "", "Optional time window the finding refers to.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
