// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSingleSessionSummariesListCmd(flags *rootFlags) *cobra.Command {
	var flagCreatedBy string
	var flagDateFrom string
	var flagDateTo string
	var flagDistinctId string
	var flagHasExceptions bool
	var flagHasVisualConfirmation bool
	var flagLimit int
	var flagOffset string
	var flagOrder string
	var flagOutcome string
	var flagSessionIds string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list <project_id>",
		Aliases:     []string{"get"},
		Short:       "List stored AI-generated session summaries for the team, one row per session (latest summary kept).",
		Example:     "  posthog-pp-cli single-session-summaries list 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "single-session-summaries.list", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/single_session_summaries/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"-created_at", "-session_duration", "-session_start_time", "created_at", "session_duration", "session_start_time"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagOrder, "order", allowedOrder)
				}
			}
			if cmd.Flags().Changed("outcome") {
				allowedOutcome := []string{"failure", "success", "unknown"}
				validOutcome := false
				for _, v := range allowedOutcome {
					if flagOutcome == v {
						validOutcome = true
						break
					}
				}
				if !validOutcome {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagOutcome, "outcome", allowedOutcome)
				}
			}
			path := "/api/projects/{project_id}/single_session_summaries/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "single-session-summaries", path, map[string]string{
				"created_by":              formatCLIParamValue(flagCreatedBy),
				"date_from":               formatCLIParamValue(flagDateFrom),
				"date_to":                 formatCLIParamValue(flagDateTo),
				"distinct_id":             formatCLIParamValue(flagDistinctId),
				"has_exceptions":          formatCLIParamValue(flagHasExceptions),
				"has_visual_confirmation": formatCLIParamValue(flagHasVisualConfirmation),
				"limit":                   formatCLIParamValue(flagLimit),
				"offset":                  formatCLIParamValue(flagOffset),
				"order":                   formatCLIParamValue(flagOrder),
				"outcome":                 formatCLIParamValue(flagOutcome),
				"session_ids":             formatCLIParamValue(flagSessionIds),
			}, nil, flagAll, "offset", "offset", "limit", 100, "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagCreatedBy, "created-by", "", "Filter to summaries triggered by a specific user, identified by `User.uuid`.")
	cmd.Flags().StringVar(&flagDateFrom, "date-from", "", "Inclusive lower bound on `created_at`, accepts relative shorthand like `-7d`.")
	cmd.Flags().StringVar(&flagDateTo, "date-to", "", "Inclusive upper bound on `created_at`, accepts relative shorthand like `-1d`.")
	cmd.Flags().StringVar(&flagDistinctId, "distinct-id", "", "Filter to summaries for a single user (the session's `distinct_id`).")
	cmd.Flags().BoolVar(&flagHasExceptions, "has-exceptions", false, "When true, only summaries that surfaced one or more exception events; when false, only summaries without exceptions.")
	cmd.Flags().BoolVar(&flagHasVisualConfirmation, "has-visual-confirmation", false, "When true, only summaries produced via the video-based visual-confirmation workflow.")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Number of results to return per page.")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "The initial index from which to return the results.")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Ordering field, defaults to `-created_at` (most recent first). (one of: -created_at, -session_duration, -session_start_time, created_at, session_duration, session_start_time)")
	cmd.Flags().StringVar(&flagOutcome, "outcome", "", "Filter by the summary's recorded `session_outcome.success` field. (one of: failure, success, unknown)")
	cmd.Flags().StringVar(&flagSessionIds, "session-ids", "", "Comma-separated list of session IDs to restrict the result to (uses the `(team, session_id)` index).")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
