// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStreamlitAppsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "streamlit-apps",
		Short:       "List, get, create, update, and delete streamlit apps",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStreamlitAppsCreateCmd(flags))
	cmd.AddCommand(newStreamlitAppsDestroyCmd(flags))
	cmd.AddCommand(newStreamlitAppsListCmd(flags))
	cmd.AddCommand(newStreamlitAppsPartialUpdateCmd(flags))
	cmd.AddCommand(newStreamlitAppsRetrieveCmd(flags))
	cmd.AddCommand(newStreamlitAppsUpdateCmd(flags))
	cmd.AddCommand(newStreamlitAppsActivateVersionCmd(flags))
	cmd.AddCommand(newStreamlitAppsConnectInfoCmd(flags))
	cmd.AddCommand(newStreamlitAppsCreateVersionFromSourceCmd(flags))
	cmd.AddCommand(newStreamlitAppsRestartCmd(flags))
	cmd.AddCommand(newStreamlitAppsStartCmd(flags))
	cmd.AddCommand(newStreamlitAppsStatusCmd(flags))
	cmd.AddCommand(newStreamlitAppsStopCmd(flags))
	cmd.AddCommand(newStreamlitAppsUploadVersionCmd(flags))
	cmd.AddCommand(newStreamlitAppsVersionsCmd(flags))
	return cmd
}
