// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newSubscriptionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAiPromptConfigWindowEndDaysAgo int
	var bodyAiPromptConfigWindowMode string
	var bodyAiPromptConfigWindowStartDaysAgo int
	var bodyBysetpos int
	var bodyByweekday string
	var bodyCount int
	var bodyCreatedAt string
	var bodyCreatedByDistinctId string
	var bodyCreatedByEmail string
	var bodyCreatedByFirstName string
	var bodyCreatedByHedgehogConfig string
	var bodyCreatedById string
	var bodyCreatedByIsEmailVerified bool
	var bodyCreatedByLastName string
	var bodyCreatedByRoleAtOrganization string
	var bodyCreatedByUuid string
	var bodyDashboard int
	var bodyDashboardExportInsights string
	var bodyDeleted bool
	var bodyEnabled bool
	var bodyFrequency string
	var bodyId string
	var bodyInsight int
	var bodyInsightShortId string
	var bodyIntegrationId string
	var bodyInterval int
	var bodyInviteMessage string
	var bodyNextDeliveryDate string
	var bodyPrompt string
	var bodyResourceName string
	var bodyResourceType string
	var bodySendTestNow bool
	var bodyStartDate string
	var bodySummary string
	var bodySummaryEnabled bool
	var bodySummaryPromptGuide string
	var bodyTargetType string
	var bodyTargetValue string
	var bodyTitle string
	var bodyUntilDate string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <project_id>",
		Short:       "Create",
		Example:     "  posthog-pp-cli subscriptions create 550e8400-e29b-41d4-a716-446655440000 --created-at 2026-01-15T09:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "subscriptions.create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/subscriptions/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("created-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-at")
				}
				if !cmd.Flags().Changed("created-by-email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-email")
				}
				if !cmd.Flags().Changed("created-by-hedgehog-config") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-hedgehog-config")
				}
				if !cmd.Flags().Changed("created-by-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-id")
				}
				if !cmd.Flags().Changed("created-by-uuid") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "created-by-uuid")
				}
				if !cmd.Flags().Changed("frequency") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "frequency")
				}
				if !cmd.Flags().Changed("id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "id")
				}
				if !cmd.Flags().Changed("insight-short-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "insight-short-id")
				}
				if !cmd.Flags().Changed("interval") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "interval")
				}
				if !cmd.Flags().Changed("next-delivery-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "next-delivery-date")
				}
				if !cmd.Flags().Changed("resource-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "resource-name")
				}
				if !cmd.Flags().Changed("resource-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "resource-type")
				}
				if !cmd.Flags().Changed("start-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "start-date")
				}
				if !cmd.Flags().Changed("summary") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "summary")
				}
				if !cmd.Flags().Changed("target-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "target-type")
				}
				if !cmd.Flags().Changed("target-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "target-value")
				}
			}
			path := "/api/projects/{project_id}/subscriptions/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedAiPromptConfig := map[string]any{}
					{
						nestedAiPromptConfigWindow := map[string]any{}
						if bodyAiPromptConfigWindowEndDaysAgo != 0 {
							nestedAiPromptConfigWindow["end_days_ago"] = bodyAiPromptConfigWindowEndDaysAgo
						}
						if bodyAiPromptConfigWindowMode != "" {
							nestedAiPromptConfigWindow["mode"] = bodyAiPromptConfigWindowMode
						}
						if bodyAiPromptConfigWindowStartDaysAgo != 0 {
							nestedAiPromptConfigWindow["start_days_ago"] = bodyAiPromptConfigWindowStartDaysAgo
						}
						if len(nestedAiPromptConfigWindow) > 0 {
							nestedAiPromptConfig["window"] = nestedAiPromptConfigWindow
						}
					}
					if len(nestedAiPromptConfig) > 0 {
						bodyMap["ai_prompt_config"] = nestedAiPromptConfig
					}
				}
				if bodyBysetpos != 0 {
					bodyMap["bysetpos"] = bodyBysetpos
				}
				if cmd.Flags().Changed("byweekday") {
					parsedByweekday, parseErr := cliutil.ParseStringList(bodyByweekday)
					if parseErr != nil {
						return fmt.Errorf("parsing --byweekday list: %w", parseErr)
					}
					bodyMap["byweekday"] = parsedByweekday
				}
				if bodyCount != 0 {
					bodyMap["count"] = bodyCount
				}
				if bodyCreatedAt != "" {
					bodyMap["created_at"] = bodyCreatedAt
				}
				{
					nestedCreatedBy := map[string]any{}
					if bodyCreatedByDistinctId != "" {
						nestedCreatedBy["distinct_id"] = bodyCreatedByDistinctId
					}
					if bodyCreatedByEmail != "" {
						nestedCreatedBy["email"] = bodyCreatedByEmail
					}
					if bodyCreatedByFirstName != "" {
						nestedCreatedBy["first_name"] = bodyCreatedByFirstName
					}
					if bodyCreatedByHedgehogConfig != "" {
						var parsedCreatedByHedgehogConfig any
						if err := json.Unmarshal([]byte(bodyCreatedByHedgehogConfig), &parsedCreatedByHedgehogConfig); err != nil {
							return fmt.Errorf("parsing --created-by-hedgehog-config JSON: %w", err)
						}
						asMap, ok := parsedCreatedByHedgehogConfig.(map[string]any)
						if !ok {
							return fmt.Errorf("--created-by-hedgehog-config must be a JSON object, got JSON %T", parsedCreatedByHedgehogConfig)
						}
						nestedCreatedBy["hedgehog_config"] = asMap
					}
					if bodyCreatedById != "" {
						nestedCreatedBy["id"] = bodyCreatedById
					}
					if cmd.Flags().Changed("created-by-is-email-verified") {
						nestedCreatedBy["is_email_verified"] = bodyCreatedByIsEmailVerified
					}
					if bodyCreatedByLastName != "" {
						nestedCreatedBy["last_name"] = bodyCreatedByLastName
					}
					if bodyCreatedByRoleAtOrganization != "" {
						nestedCreatedBy["role_at_organization"] = bodyCreatedByRoleAtOrganization
					}
					if bodyCreatedByUuid != "" {
						nestedCreatedBy["uuid"] = bodyCreatedByUuid
					}
					if len(nestedCreatedBy) > 0 {
						bodyMap["created_by"] = nestedCreatedBy
					}
				}
				if bodyDashboard != 0 {
					bodyMap["dashboard"] = bodyDashboard
				}
				if bodyDashboardExportInsights != "" {
					var parsedDashboardExportInsights any
					if err := json.Unmarshal([]byte(bodyDashboardExportInsights), &parsedDashboardExportInsights); err != nil {
						return fmt.Errorf("parsing --dashboard-export-insights JSON: %w", err)
					}
					asArray, ok := parsedDashboardExportInsights.([]any)
					if !ok {
						return fmt.Errorf("--dashboard-export-insights must be a JSON array, got JSON %T", parsedDashboardExportInsights)
					}
					bodyMap["dashboard_export_insights"] = asArray
				}
				if cmd.Flags().Changed("deleted") {
					bodyMap["deleted"] = bodyDeleted
				}
				if cmd.Flags().Changed("enabled") {
					bodyMap["enabled"] = bodyEnabled
				}
				if bodyFrequency != "" {
					bodyMap["frequency"] = bodyFrequency
				}
				if bodyId != "" {
					bodyMap["id"] = bodyId
				}
				if bodyInsight != 0 {
					bodyMap["insight"] = bodyInsight
				}
				if bodyInsightShortId != "" {
					bodyMap["insight_short_id"] = bodyInsightShortId
				}
				if bodyIntegrationId != "" {
					bodyMap["integration_id"] = bodyIntegrationId
				}
				if bodyInterval != 0 {
					bodyMap["interval"] = bodyInterval
				}
				if bodyInviteMessage != "" {
					bodyMap["invite_message"] = bodyInviteMessage
				}
				if bodyNextDeliveryDate != "" {
					bodyMap["next_delivery_date"] = bodyNextDeliveryDate
				}
				if bodyPrompt != "" {
					bodyMap["prompt"] = bodyPrompt
				}
				if bodyResourceName != "" {
					bodyMap["resource_name"] = bodyResourceName
				}
				if bodyResourceType != "" {
					bodyMap["resource_type"] = bodyResourceType
				}
				if cmd.Flags().Changed("send-test-now") {
					bodyMap["send_test_now"] = bodySendTestNow
				}
				if bodyStartDate != "" {
					bodyMap["start_date"] = bodyStartDate
				}
				if bodySummary != "" {
					bodyMap["summary"] = bodySummary
				}
				if cmd.Flags().Changed("summary-enabled") {
					bodyMap["summary_enabled"] = bodySummaryEnabled
				}
				if bodySummaryPromptGuide != "" {
					bodyMap["summary_prompt_guide"] = bodySummaryPromptGuide
				}
				if bodyTargetType != "" {
					bodyMap["target_type"] = bodyTargetType
				}
				if bodyTargetValue != "" {
					bodyMap["target_value"] = bodyTargetValue
				}
				if bodyTitle != "" {
					bodyMap["title"] = bodyTitle
				}
				if bodyUntilDate != "" {
					bodyMap["until_date"] = bodyUntilDate
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "subscriptions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "subscriptions", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "subscriptions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "subscriptions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "subscriptions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "subscriptions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "subscriptions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "subscriptions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().IntVar(&bodyAiPromptConfigWindowEndDaysAgo, "ai-prompt-config-window-end-days-ago", 0, "Upper bound of the analysis window, in days before the run (0 = now).")
	cmd.Flags().StringVar(&bodyAiPromptConfigWindowMode, "ai-prompt-config-window-mode", "", "What the report analyzes each run: * `since_last_sent` (default)")
	cmd.Flags().IntVar(&bodyAiPromptConfigWindowStartDaysAgo, "ai-prompt-config-window-start-days-ago", 0, "Lower bound of the analysis window, in days before the run.")
	cmd.Flags().IntVar(&bodyBysetpos, "bysetpos", 0, "Position within byweekday set for monthly frequency (e.g. 1 for first, -1 for last).")
	cmd.Flags().StringVar(&bodyByweekday, "byweekday", "", "Days of week for daily or weekly subscriptions: monday, tuesday, wednesday, thursday, friday, saturday, sunday.")
	cmd.Flags().IntVar(&bodyCount, "count", 0, "Total number of deliveries before the subscription stops. Null for unlimited.")
	cmd.Flags().StringVar(&bodyCreatedAt, "created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyCreatedByDistinctId, "created-by-distinct-id", "", "Distinct id")
	cmd.Flags().StringVar(&bodyCreatedByEmail, "created-by-email", "", "Email")
	cmd.Flags().StringVar(&bodyCreatedByFirstName, "created-by-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyCreatedByHedgehogConfig, "created-by-hedgehog-config", "", "Hedgehog config")
	cmd.Flags().StringVar(&bodyCreatedById, "created-by-id", "", "Id")
	cmd.Flags().BoolVar(&bodyCreatedByIsEmailVerified, "created-by-is-email-verified", false, "Is email verified")
	cmd.Flags().StringVar(&bodyCreatedByLastName, "created-by-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyCreatedByRoleAtOrganization, "created-by-role-at-organization", "", "Role at organization")
	cmd.Flags().StringVar(&bodyCreatedByUuid, "created-by-uuid", "", "Uuid")
	cmd.Flags().IntVar(&bodyDashboard, "dashboard", 0, "Dashboard ID to subscribe to (mutually exclusive with insight on create).")
	cmd.Flags().StringVar(&bodyDashboardExportInsights, "dashboard-export-insights", "", "List of insight IDs from the dashboard to include. Required for dashboard subscriptions, max 10.")
	cmd.Flags().BoolVar(&bodyDeleted, "deleted", false, "Set to true to soft-delete. Subscriptions cannot be hard-deleted.")
	cmd.Flags().BoolVar(&bodyEnabled, "enabled", false, "Whether the subscription is active. Set to false to pause delivery without deleting.")
	cmd.Flags().StringVar(&bodyFrequency, "frequency", "", "How often to deliver: daily, weekly, monthly, or yearly.")
	cmd.Flags().StringVar(&bodyId, "id", "", "Id")
	cmd.Flags().IntVar(&bodyInsight, "insight", 0, "Insight ID to subscribe to (mutually exclusive with dashboard on create).")
	cmd.Flags().StringVar(&bodyInsightShortId, "insight-short-id", "", "Insight short id")
	cmd.Flags().StringVar(&bodyIntegrationId, "integration-id", "", "ID of a connected Slack integration. Required when target_type is slack.")
	cmd.Flags().IntVar(&bodyInterval, "interval", 0, "Interval multiplier (e.g. 2 with weekly frequency means every 2 weeks). Required on create; must be 1 or greater.")
	cmd.Flags().StringVar(&bodyInviteMessage, "invite-message", "", "Optional message included in the invitation email when adding new recipients.")
	cmd.Flags().StringVar(&bodyNextDeliveryDate, "next-delivery-date", "", "Next delivery date")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "Free-text prompt that drives the AI-generated report. Required when resource_type is 'ai_prompt'. Max 4000 characters.")
	cmd.Flags().StringVar(&bodyResourceName, "resource-name", "", "Resource name")
	cmd.Flags().StringVar(&bodyResourceType, "resource-type", "", "What the subscription delivers: 'insight' (snapshot of one insight), 'dashboard' (snapshot of one dashboard)")
	cmd.Flags().BoolVar(&bodySendTestNow, "send-test-now", false, "Whether to immediately deliver the subscription once on save so the editor can confirm it looks right.")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "When to start delivering (ISO 8601 datetime).")
	cmd.Flags().StringVar(&bodySummary, "summary", "", "Human-readable schedule summary, e.g. 'sent daily'.")
	cmd.Flags().BoolVar(&bodySummaryEnabled, "summary-enabled", false, "Whether to attach an AI-generated summary to each delivery (insight and dashboard subscriptions only).")
	cmd.Flags().StringVar(&bodySummaryPromptGuide, "summary-prompt-guide", "", "Optional free-text guidance (max 500 chars) steering the AI summary, e.g. which metrics to emphasize.")
	cmd.Flags().StringVar(&bodyTargetType, "target-type", "", "Delivery channel: email or slack. * `email` - Email * `slack` - Slack")
	cmd.Flags().StringVar(&bodyTargetValue, "target-value", "", "Recipient(s): comma-separated email addresses for email, or Slack channel name/ID for slack.")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Human-readable name for this subscription.")
	cmd.Flags().StringVar(&bodyUntilDate, "until-date", "", "When to stop delivering (ISO 8601 datetime). Null for indefinite.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
