// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTaskAutomationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "task-automations",
		Short:       "List, get, create, update, and delete task automations",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTaskAutomationsCreateCmd(flags))
	cmd.AddCommand(newTaskAutomationsDestroyCmd(flags))
	cmd.AddCommand(newTaskAutomationsListCmd(flags))
	cmd.AddCommand(newTaskAutomationsPartialUpdateCmd(flags))
	cmd.AddCommand(newTaskAutomationsRetrieveCmd(flags))
	cmd.AddCommand(newTaskAutomationsRunCmd(flags))
	return cmd
}
