// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTasksRunsTasksLivingArtifactsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAdapter string
	var bodyArtifactType string
	var bodyContent string
	var bodyContentBase64 string
	var bodyContentType string
	var bodyMetadata string
	var bodyName string
	var bodySourceArtifactId string
	var bodySourceStoragePath string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "tasks-living-artifacts-create <project_id> <task_id> <run_id>",
		Short:       "Create a stable, editable artifact handle from direct markdown/text content or an existing run artifact.",
		Example:     "  posthog-pp-cli tasks runs tasks-living-artifacts-create 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "runs.tasks-living-artifacts-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/tasks/{task_id}/runs/{run_id}/living_artifacts/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <task_id> <run_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <task_id> <run_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
			}
			path := "/api/projects/{project_id}/tasks/{task_id}/runs/{run_id}/living_artifacts/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			if len(args) < 3 || args[2] == "" {
				return usageErr(fmt.Errorf("run_id is required\nUsage: %s <%s>", cmd.CommandPath(), "run_id"))
			}
			path = replacePathParam(path, "run_id", args[2])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("task_id is required\nUsage: %s <%s>", cmd.CommandPath(), "task_id"))
			}
			path = replacePathParam(path, "task_id", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyAdapter != "" {
					bodyMap["adapter"] = bodyAdapter
				}
				if bodyArtifactType != "" {
					bodyMap["artifact_type"] = bodyArtifactType
				}
				if bodyContent != "" {
					bodyMap["content"] = bodyContent
				}
				if bodyContentBase64 != "" {
					bodyMap["content_base64"] = bodyContentBase64
				}
				if bodyContentType != "" {
					bodyMap["content_type"] = bodyContentType
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					asMap, ok := parsedMetadata.(map[string]any)
					if !ok {
						return fmt.Errorf("--metadata must be a JSON object, got JSON %T", parsedMetadata)
					}
					bodyMap["metadata"] = asMap
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if bodySourceArtifactId != "" {
					bodyMap["source_artifact_id"] = bodySourceArtifactId
				}
				if bodySourceStoragePath != "" {
					bodyMap["source_storage_path"] = bodySourceStoragePath
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "runs", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "runs", data, "versions")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "runs", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "runs", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "runs", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "runs",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "runs", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "runs", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAdapter, "adapter", "", "Optional preferred external storage or delivery adapter.")
	cmd.Flags().StringVar(&bodyArtifactType, "artifact-type", "", "Artifact format or delivery surface to create, such as document, spreadsheet, slack_canvas, or file.")
	cmd.Flags().StringVar(&bodyContent, "content", "", "Markdown or text content for the initial artifact version.")
	cmd.Flags().StringVar(&bodyContentBase64, "content-base64", "", "Base64-encoded binary content for Slack file uploads or other external adapters.")
	cmd.Flags().StringVar(&bodyContentType, "content-type", "", "MIME type for content_base64 or source-backed artifacts, such as application/vnd.openxmlformats-officedocument.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Optional metadata to persist with the living artifact.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Human-readable artifact name, used as the title.")
	cmd.Flags().StringVar(&bodySourceArtifactId, "source-artifact-id", "", "Existing run artifact id to use as the initial content source.")
	cmd.Flags().StringVar(&bodySourceStoragePath, "source-storage-path", "", "Existing run artifact storage_path to use as the initial content source.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
