// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTasksThreadMessagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "thread-messages",
		Short:       "Get, create, and delete thread messages for tasks",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTasksThreadMessagesTasksCreateCmd(flags))
	cmd.AddCommand(newTasksThreadMessagesTasksDestroyCmd(flags))
	cmd.AddCommand(newTasksThreadMessagesTasksListCmd(flags))
	cmd.AddCommand(newTasksThreadMessagesTasksSendToAgentCreateCmd(flags))
	return cmd
}
