// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTracingSpansValuesRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagAttributeType string
	var flagKey string
	var flagLimit int
	var flagOffset string
	var flagValue string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "spans-values-retrieve <project_id>",
		Short:       "Spans values retrieve",
		Example:     "  posthog-pp-cli tracing spans-values-retrieve 550e8400-e29b-41d4-a716-446655440000 --key your-token-here",
		Annotations: map[string]string{"pp:endpoint": "tracing.spans-values-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/tracing/spans/values/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !cmd.Flags().Changed("key") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "key")
			}
			if cmd.Flags().Changed("attribute-type") {
				allowedAttributeType := []string{"span", "span_attribute", "span_resource_attribute"}
				validAttributeType := false
				for _, v := range allowedAttributeType {
					if flagAttributeType == v {
						validAttributeType = true
						break
					}
				}
				if !validAttributeType {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagAttributeType, "attribute-type", allowedAttributeType)
				}
			}
			path := "/api/projects/{project_id}/tracing/spans/values/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "tracing", path, map[string]string{
				"attribute_type": formatCLIParamValue(flagAttributeType),
				"key":            formatCLIParamValue(flagKey),
				"limit":          formatCLIParamValue(flagLimit),
				"offset":         formatCLIParamValue(flagOffset),
				"value":          formatCLIParamValue(flagValue),
			}, nil, flagAll, "offset", "offset", "limit", 100, "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagAttributeType, "attribute-type", "", "Type of attribute: 'span' for built-in span fields (e.g. (one of: span, span_attribute, span_resource_attribute)")
	cmd.Flags().StringVar(&flagKey, "key", "", "The attribute key to get values for.")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Max results (default: 100).")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Pagination offset (default: 0).")
	cmd.Flags().StringVar(&flagValue, "value", "", "Search filter for attribute values.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
