// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"posthog-pp-cli/internal/cliutil"
)

func newTracingSpansAttributeBreakdownCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyQueryBreakdownKey string
	var bodyQueryBreakdownType string
	var bodyQueryCompareFilterCompare bool
	var bodyQueryCompareFilterCompareTo string
	var bodyQueryDateRangeDateFrom string
	var bodyQueryDateRangeDateTo string
	var bodyQueryExcludeBreakdownFilter bool
	var bodyQueryFacetSearch string
	var bodyQueryFilterGroup string
	var bodyQueryOrderBy string
	var bodyQueryServiceNames string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "spans-attribute-breakdown-create <project_id>",
		Short:       "Spans attribute breakdown create",
		Example:     "  posthog-pp-cli tracing spans-attribute-breakdown-create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "tracing.spans-attribute-breakdown-create", "pp:method": "POST", "pp:path": "/api/projects/{project_id}/tracing/spans/attribute-breakdown/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("query-breakdown-key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "query-breakdown-key")
				}
				if !cmd.Flags().Changed("query-breakdown-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "query-breakdown-type")
				}
			}
			path := "/api/projects/{project_id}/tracing/spans/attribute-breakdown/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedQuery := map[string]any{}
					if bodyQueryBreakdownKey != "" {
						nestedQuery["breakdownKey"] = bodyQueryBreakdownKey
					}
					if bodyQueryBreakdownType != "" {
						nestedQuery["breakdownType"] = bodyQueryBreakdownType
					}
					{
						nestedQueryCompareFilter := map[string]any{}
						if cmd.Flags().Changed("query-compare-filter-compare") {
							nestedQueryCompareFilter["compare"] = bodyQueryCompareFilterCompare
						}
						if bodyQueryCompareFilterCompareTo != "" {
							nestedQueryCompareFilter["compare_to"] = bodyQueryCompareFilterCompareTo
						}
						if len(nestedQueryCompareFilter) > 0 {
							nestedQuery["compareFilter"] = nestedQueryCompareFilter
						}
					}
					{
						nestedQueryDateRange := map[string]any{}
						if bodyQueryDateRangeDateFrom != "" {
							nestedQueryDateRange["date_from"] = bodyQueryDateRangeDateFrom
						}
						if bodyQueryDateRangeDateTo != "" {
							nestedQueryDateRange["date_to"] = bodyQueryDateRangeDateTo
						}
						if len(nestedQueryDateRange) > 0 {
							nestedQuery["dateRange"] = nestedQueryDateRange
						}
					}
					if cmd.Flags().Changed("query-exclude-breakdown-filter") {
						nestedQuery["excludeBreakdownFilter"] = bodyQueryExcludeBreakdownFilter
					}
					if bodyQueryFacetSearch != "" {
						nestedQuery["facetSearch"] = bodyQueryFacetSearch
					}
					if bodyQueryFilterGroup != "" {
						var parsedQueryFilterGroup any
						if err := json.Unmarshal([]byte(bodyQueryFilterGroup), &parsedQueryFilterGroup); err != nil {
							return fmt.Errorf("parsing --query-filter-group JSON: %w", err)
						}
						asArray, ok := parsedQueryFilterGroup.([]any)
						if !ok {
							return fmt.Errorf("--query-filter-group must be a JSON array, got JSON %T", parsedQueryFilterGroup)
						}
						nestedQuery["filterGroup"] = asArray
					}
					if bodyQueryOrderBy != "" {
						nestedQuery["orderBy"] = bodyQueryOrderBy
					}
					if cmd.Flags().Changed("query-service-names") {
						parsedQueryServiceNames, parseErr := cliutil.ParseStringList(bodyQueryServiceNames)
						if parseErr != nil {
							return fmt.Errorf("parsing --query-service-names list: %w", parseErr)
						}
						nestedQuery["serviceNames"] = parsedQueryServiceNames
					}
					if len(nestedQuery) > 0 {
						bodyMap["query"] = nestedQuery
					}
				}
			}
			data, statusCode, err := c.PostQueryWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "tracing", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tracing", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tracing", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tracing", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "tracing",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tracing", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tracing", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyQueryBreakdownKey, "query-breakdown-key", "", "Attribute key to group by (e.g. 'server.address', 'http.response.status_code'). Discover keys with apm-attributes-list.")
	cmd.Flags().StringVar(&bodyQueryBreakdownType, "query-breakdown-type", "", "Where the key lives: 'span' for allowlisted top-level span columns, 'span_attribute' for span-level attributes")
	cmd.Flags().BoolVar(&bodyQueryCompareFilterCompare, "query-compare-filter-compare", false, "When true, also fetch results for a comparison window and return them under `compare`.")
	cmd.Flags().StringVar(&bodyQueryCompareFilterCompareTo, "query-compare-filter-compare-to", "", "Relative date offset for the comparison window (e.g. '-1h', '-1d', '-7d').")
	cmd.Flags().StringVar(&bodyQueryDateRangeDateFrom, "query-date-range-date-from", "", "Start of the date range. Accepts ISO 8601 timestamps or relative formats: -1h, -6h, -1d, -7d, etc.")
	cmd.Flags().StringVar(&bodyQueryDateRangeDateTo, "query-date-range-date-to", "", "End of the date range. Same format as date_from. Omit or null for 'now'.")
	cmd.Flags().BoolVar(&bodyQueryExcludeBreakdownFilter, "query-exclude-breakdown-filter", false, "Drop filters targeting the breakdown key itself (including serviceNames for a service_name breakdown)")
	cmd.Flags().StringVar(&bodyQueryFacetSearch, "query-facet-search", "", "Type-ahead filter over the breakdown field's own values (case-insensitive substring match).")
	cmd.Flags().StringVar(&bodyQueryFilterGroup, "query-filter-group", "", "Property filters scoping the spans the breakdown runs over (e.g. only error spans).")
	cmd.Flags().StringVar(&bodyQueryOrderBy, "query-order-by", "", "Order rows by span count or error count, descending. Defaults to count. * `count` - count * `error_count` - error_count")
	cmd.Flags().StringVar(&bodyQueryServiceNames, "query-service-names", "", "Filter by service names.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
