// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserInterviewTopicsIntervieweesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "interviewees",
		Short:       "Get, create, update, and delete interviewees for user interview topics",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsBulkCreateCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsCreateCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsDestroyCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsListCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsPartialUpdateCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsRetrieveCmd(flags))
	cmd.AddCommand(newUserInterviewTopicsIntervieweesUserInterviewTopicsUpdateCmd(flags))
	return cmd
}
