// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVisionScannersObservationsStatsRetrieveCmd(flags *rootFlags) *cobra.Command {
	var flagDateFrom string
	var flagDateTo string
	var flagLabeled string
	var flagRecentDays int
	var flagRecordingSubject string
	var flagSessionId string
	var flagStatus string
	var flagTags string
	var flagTriggeredBy string
	var flagVerdict string

	cmd := &cobra.Command{
		Use:         "scanners-observations-stats-retrieve <project_id> <scanner_id>",
		Short:       "Aggregate counts and per-scanner-type distributions over the filtered observation set.",
		Example:     "  posthog-pp-cli vision scanners-observations-stats-retrieve 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "vision.scanners-observations-stats-retrieve", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/vision/scanners/{scanner_id}/observations/stats/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id> <scanner_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id> <scanner_id>"))
			}
			path := "/api/projects/{project_id}/vision/scanners/{scanner_id}/observations/stats/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("scanner_id is required\nUsage: %s <%s>", cmd.CommandPath(), "scanner_id"))
			}
			path = replacePathParam(path, "scanner_id", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagDateFrom != "" {
				params["date_from"] = formatCLIParamValue(flagDateFrom)
			}
			if flagDateTo != "" {
				params["date_to"] = formatCLIParamValue(flagDateTo)
			}
			if flagLabeled != "" {
				params["labeled"] = formatCLIParamValue(flagLabeled)
			}
			if flagRecentDays != 0 {
				params["recent_days"] = formatCLIParamValue(flagRecentDays)
			}
			if flagRecordingSubject != "" {
				params["recording_subject"] = formatCLIParamValue(flagRecordingSubject)
			}
			if flagSessionId != "" {
				params["session_id"] = formatCLIParamValue(flagSessionId)
			}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			if flagTags != "" {
				params["tags"] = formatCLIParamValue(flagTags)
			}
			if flagTriggeredBy != "" {
				params["triggered_by"] = formatCLIParamValue(flagTriggeredBy)
			}
			if flagVerdict != "" {
				params["verdict"] = formatCLIParamValue(flagVerdict)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "vision", false, path, params, nil, "available_tags", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagDateFrom, "date-from", "", "Only observations created at or after this time.")
	cmd.Flags().StringVar(&flagDateTo, "date-to", "", "Only observations created at or before this time.")
	cmd.Flags().StringVar(&flagLabeled, "labeled", "", "When true, return only observations that have a shared label (thumbs up or down); when false")
	cmd.Flags().IntVar(&flagRecentDays, "recent-days", 0, "Window size in days for the coverage `recent_sessions` count. Clamped to [1, 365]. Defaults to 14 when omitted.")
	cmd.Flags().StringVar(&flagRecordingSubject, "recording-subject", "", "Filter to observations whose person email contains this value (case-insensitive).")
	cmd.Flags().StringVar(&flagSessionId, "session-id", "", "Filter to observations of one or more session recordings. Accepts a comma-separated list.")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter by observation status. Accepts a comma-separated list.")
	cmd.Flags().StringVar(&flagTags, "tags", "", "Filter classifier observations whose fixed or freeform tags include any of the given values (comma-separated).")
	cmd.Flags().StringVar(&flagTriggeredBy, "triggered-by", "", "Filter by trigger source (schedule, on_demand, or retry). Accepts a comma-separated list.")
	cmd.Flags().StringVar(&flagVerdict, "verdict", "", "Filter monitor observations by verdict. Accepts a comma-separated list (e.g. `yes,inconclusive`).")

	return cmd
}
