// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVisualReviewRunsListCmd(flags *rootFlags) *cobra.Command {
	var flagBranch string
	var flagCommitSha string
	var flagLimit int
	var flagOffset string
	var flagPrNumber int
	var flagReviewState string
	var flagSearch string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "runs-list <project_id>",
		Short:       "List runs for the team, optionally filtered by review state, PR number, commit SHA, branch, or free-text search.",
		Example:     "  posthog-pp-cli visual-review runs-list 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "visual-review.runs-list", "pp:method": "GET", "pp:path": "/api/projects/{project_id}/visual_review/runs/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <project_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <project_id>"))
			}
			path := "/api/projects/{project_id}/visual_review/runs/"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "visual-review", path, map[string]string{
				"branch":       formatCLIParamValue(flagBranch),
				"commit_sha":   formatCLIParamValue(flagCommitSha),
				"limit":        formatCLIParamValue(flagLimit),
				"offset":       formatCLIParamValue(flagOffset),
				"pr_number":    formatCLIParamValue(flagPrNumber),
				"review_state": formatCLIParamValue(flagReviewState),
				"search":       formatCLIParamValue(flagSearch),
			}, nil, flagAll, "offset", "offset", "limit", 100, "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagBranch, "branch", "", "Filter by branch name")
	cmd.Flags().StringVar(&flagCommitSha, "commit-sha", "", "Filter by full commit SHA")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Number of results to return per page.")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "The initial index from which to return the results.")
	cmd.Flags().IntVar(&flagPrNumber, "pr-number", 0, "Filter by GitHub PR number")
	cmd.Flags().StringVar(&flagReviewState, "review-state", "", "Filter by review state")
	cmd.Flags().StringVar(&flagSearch, "search", "", "Free-text search over branch, commit SHA, run type, and PR number")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
