// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSceneCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "scene",
		Short:       "SCENE+ account calls using the separate browser cookie session",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSceneGetGiftCardsCmd(flags))
	cmd.AddCommand(newSceneGetLoginStatusCmd(flags))
	cmd.AddCommand(newSceneGetPayPalInformationCmd(flags))
	cmd.AddCommand(newSceneGetPaymentCardsCmd(flags))
	cmd.AddCommand(newSceneGetSceneInfoCmd(flags))
	cmd.AddCommand(newSceneGetUserProfileInfoCmd(flags))
	return cmd
}
