// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAdGroupsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyOperations string

	cmd := &cobra.Command{
		Use:         "ad-groups <customerId>",
		Short:       "Create, update, or remove ad groups",
		Long:        "Create, update, or remove ad groups",
		Example:     `# list ad groups before deciding which to adjust bids on
google-ads ad-groups 1234567890

# bulk create new ad groups from generated ops file
google-ads ad-groups 1234567890 --operations "$(cat new_ad_groups.json)"`,
		Annotations: map[string]string{"pp:endpoint": "adGroups.mutate", "pp:method": "POST", "pp:path": "/v24/customers/{customerId}/adGroups:mutate"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v24/customers/{customerId}/adGroups:mutate"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "customerId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "customerId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("customerId is required\nUsage: %s <%s>", cmd.CommandPath(), "customerId"))
			}
			path = replacePathParam(path, "customerId", args[0])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if bodyOperations != "" {
				var parsedOperations any
				if err := json.Unmarshal([]byte(bodyOperations), &parsedOperations); err != nil {
					return fmt.Errorf("parsing --operations JSON: %w", err)
				}
				asArray, ok := parsedOperations.([]any)
				if !ok {
					return fmt.Errorf("--operations must be a JSON array, got JSON %T", parsedOperations)
				}
				bodyMap["operations"] = asArray
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "adgroups", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&bodyOperations, "operations", "", "List of ad group mutate operations")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
