// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type ExportDataGetProjectLiveInsightsItem struct {
	Information json.RawMessage `json:"information"`
	MetricName  string          `json:"metricName"`
}
