// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGoogleAnalyticsAdminPropertiesSearchAds360LinksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "search-ads360-links",
		Short:       "Manage search ads360 links",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesSearchAds360LinksCreateCmd(flags))
	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesSearchAds360LinksListCmd(flags))
	return cmd
}
