// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGoogleAnalyticsAdminPropertiesDisplayVideo360AdvertiserLinkProposalsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "display-video360-advertiser-link-proposals",
		Short:       "Manage display video360 advertiser link proposals",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesDisplayVideo360AdvertiserLinkProposalsApproveCmd(flags))
	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesDisplayVideo360AdvertiserLinkProposalsCancelCmd(flags))
	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesDisplayVideo360AdvertiserLinkProposalsCreateCmd(flags))
	cmd.AddCommand(newGoogleAnalyticsAdminPropertiesDisplayVideo360AdvertiserLinkProposalsListCmd(flags))
	return cmd
}
