// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newActAdAccountIdGetAdAccountInsightsCmd(flags *rootFlags) *cobra.Command {
	var flagFields string
	var flagDatePreset string
	var flagTimeRange string
	var flagLevel string
	var flagBreakdowns string

	cmd := &cobra.Command{
		Use:         "get-ad-account-insights <ad_account_id>",
		Short:       "Get performance insights for an ad account (reporting)",
		Example:     "  meta-ads-pp-cli act-ad-account-id get-ad-account-insights 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "act-ad-account-id.get-ad-account-insights", "pp:method": "GET", "pp:path": "/act_{ad_account_id}/insights", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <ad_account_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <ad_account_id>"))
			}
			if cmd.Flags().Changed("level") {
				allowedLevel := []string{"account", "campaign", "adset", "ad"}
				validLevel := false
				for _, v := range allowedLevel {
					if flagLevel == v {
						validLevel = true
						break
					}
				}
				if !validLevel {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagLevel, "level", allowedLevel)
				}
			}
			if cmd.Flags().Changed("time-range") {
				var parsedTimeRange any
				if err := json.Unmarshal([]byte(flagTimeRange), &parsedTimeRange); err != nil {
					return fmt.Errorf("--time-range must be valid JSON: %w", err)
				}
			}
			path := "/act_{ad_account_id}/insights"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("ad_account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "ad_account_id"))
			}
			path = replacePathParam(path, "ad_account_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagFields != "" {
				params["fields"] = formatCLIParamValue(flagFields)
			}
			if flagDatePreset != "" {
				params["date_preset"] = formatCLIParamValue(flagDatePreset)
			}
			if flagTimeRange != "" {
				params["time_range"] = formatCLIParamValue(flagTimeRange)
			}
			if flagLevel != "" {
				params["level"] = formatCLIParamValue(flagLevel)
			}
			if flagBreakdowns != "" {
				params["breakdowns"] = formatCLIParamValue(flagBreakdowns)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "act-ad-account-id", false, path, params, nil, "data", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagFields, "fields", "", "Metric fields, e.g. impressions,clicks,spend,ctr,cpc.")
	cmd.Flags().StringVar(&flagDatePreset, "date-preset", "", "e.g. last_7d, last_30d, this_month.")
	cmd.Flags().StringVar(&flagTimeRange, "time-range", "", "JSON-encoded {since,until} to override date_preset.")
	cmd.Flags().StringVar(&flagLevel, "level", "", "Level (one of: account, campaign, adset, ad)")
	cmd.Flags().StringVar(&flagBreakdowns, "breakdowns", "", "e.g. age,gender,device_platform.")

	return cmd
}
