// Copyright 2026 Pooria Arab and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"google-analytics-solo-pp-cli/internal/mcp/bound"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("google-analytics_search",
			mcplib.WithDescription("Search the google-analytics API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("google-analytics_execute",
			mcplib.WithDescription("Execute one google-analytics API endpoint by its endpoint_id (from google-analytics_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by google-analytics_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName   string
	WireName     string
	QueryArray   bool
	QueryStyle   string
	QueryExplode bool
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "account-summaries.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/accountSummaries",
		Summary:        "Returns summaries of all accounts accessible by the caller.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("account-summaries", "list", "Returns summaries of all accounts accessible by the caller.", "https://analyticsadmin.googleapis.com/v1alpha/accountSummaries"),
	},
	{
		ID:             "accounts.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/accounts",
		Summary:        "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}, {PublicName: "showDeleted", WireName: "showDeleted"}},
		keywords:       codeOrchKeywords("accounts", "list", "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties.", "https://analyticsadmin.googleapis.com/v1alpha/accounts"),
	},
	{
		ID:             "accounts.search-change-history-events",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{account}:searchChangeHistoryEvents",
		Summary:        "Searches through all changes to an account or its children given the specified set of filters.",
		Positional:     []string{"account"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("accounts", "search-change-history-events", "Searches through all changes to an account or its children given the specified set of filters.", "https://analyticsadmin.googleapis.com/v1alpha/{account}:searchChangeHistoryEvents"),
	},
	{
		ID:             "accounts-provision-account-ticket.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/accounts:provisionAccountTicket",
		Summary:        "Requests a ticket for creating an account.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("accounts-provision-account-ticket", "analyticsadmin", "Requests a ticket for creating an account.", "https://analyticsadmin.googleapis.com/v1alpha/accounts:provisionAccountTicket"),
	},
	{
		ID:             "data-streams.measurement-protocol-secrets.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/measurementProtocolSecrets",
		Summary:        "Creates a measurement protocol secret.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("data-streams", "create", "Creates a measurement protocol secret.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/measurementProtocolSecrets"),
	},
	{
		ID:             "data-streams.measurement-protocol-secrets.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/measurementProtocolSecrets",
		Summary:        "Returns child MeasurementProtocolSecrets under the specified parent Property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("data-streams", "list", "Returns child MeasurementProtocolSecrets under the specified parent Property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/measurementProtocolSecrets"),
	},
	{
		ID:             "google-analytics-admin-properties.acknowledge-user-data-collection",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{property}:acknowledgeUserDataCollection",
		Summary:        "Acknowledges the terms of user data collection for the specified property.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "acknowledge-user-data-collection", "Acknowledges the terms of user data collection for the specified property.", "https://analyticsadmin.googleapis.com/v1alpha/{property}:acknowledgeUserDataCollection"),
	},
	{
		ID:             "google-analytics-admin-properties.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties",
		Summary:        "Creates an 'GA4' property with the specified location and attributes.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates an 'GA4' property with the specified location and attributes.", "https://analyticsadmin.googleapis.com/v1alpha/properties"),
	},
	{
		ID:             "google-analytics-admin-properties.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties",
		Summary:        "Returns child Properties under the specified parent Account. Only 'GA4' properties will be returned.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "filter", WireName: "filter"}, {PublicName: "pageSize", WireName: "pageSize"}, {PublicName: "showDeleted", WireName: "showDeleted"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Returns child Properties under the specified parent Account. Only 'GA4' properties will be returned.", "https://analyticsadmin.googleapis.com/v1alpha/properties"),
	},
	{
		ID:             "google-analytics-admin-properties.run-access-report",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{entity}:runAccessReport",
		Summary:        "Returns a customized report of data access records.",
		Positional:     []string{"entity"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "run-access-report", "Returns a customized report of data access records.", "https://analyticsadmin.googleapis.com/v1alpha/{entity}:runAccessReport"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.batch-create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchCreate",
		Summary:        "Creates information about multiple access bindings to an account or property. This method is transactional.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-create", "Creates information about multiple access bindings to an account or property. This method is transactional.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchCreate"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.batch-delete",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchDelete",
		Summary:        "Deletes information about multiple users' links to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-delete", "Deletes information about multiple users' links to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchDelete"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.batch-get",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchGet",
		Summary:        "Gets information about multiple access bindings to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "names", WireName: "names", QueryArray: true, QueryStyle: "form", QueryExplode: true}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-get", "Gets information about multiple access bindings to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchGet"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.batch-update",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchUpdate",
		Summary:        "Updates information about multiple access bindings to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-update", "Updates information about multiple access bindings to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings:batchUpdate"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings",
		Summary:        "Creates an access binding on an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates an access binding on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings"),
	},
	{
		ID:             "google-analytics-admin-properties.access-bindings.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings",
		Summary:        "Lists all access bindings on an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists all access bindings on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/accessBindings"),
	},
	{
		ID:             "google-analytics-admin-properties.audiences.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/audiences",
		Summary:        "Creates an Audience.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates an Audience.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/audiences"),
	},
	{
		ID:             "google-analytics-admin-properties.audiences.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/audiences",
		Summary:        "Lists Audiences on a property. Audiences created before 2020 may not be supported.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists Audiences on a property. Audiences created before 2020 may not be supported.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/audiences"),
	},
	{
		ID:             "google-analytics-admin-properties.big-query-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/bigQueryLinks",
		Summary:        "Lists BigQuery Links on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists BigQuery Links on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/bigQueryLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.channel-groups.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/channelGroups",
		Summary:        "Creates a ChannelGroup.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a ChannelGroup.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/channelGroups"),
	},
	{
		ID:             "google-analytics-admin-properties.channel-groups.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/channelGroups",
		Summary:        "Lists ChannelGroups on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists ChannelGroups on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/channelGroups"),
	},
	{
		ID:             "google-analytics-admin-properties.conversion-events.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/conversionEvents",
		Summary:        "Creates a conversion event with the specified attributes.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a conversion event with the specified attributes.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/conversionEvents"),
	},
	{
		ID:             "google-analytics-admin-properties.conversion-events.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/conversionEvents",
		Summary:        "Returns a list of conversion events in the specified parent property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Returns a list of conversion events in the specified parent property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/conversionEvents"),
	},
	{
		ID:             "google-analytics-admin-properties.custom-dimensions.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customDimensions",
		Summary:        "Creates a CustomDimension.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a CustomDimension.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customDimensions"),
	},
	{
		ID:             "google-analytics-admin-properties.custom-dimensions.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customDimensions",
		Summary:        "Lists CustomDimensions on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists CustomDimensions on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customDimensions"),
	},
	{
		ID:             "google-analytics-admin-properties.custom-metrics.archive",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}:archive",
		Summary:        "Archives a CustomMetric on a property.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "archive", "Archives a CustomMetric on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{name}:archive"),
	},
	{
		ID:             "google-analytics-admin-properties.custom-metrics.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customMetrics",
		Summary:        "Creates a CustomMetric.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a CustomMetric.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customMetrics"),
	},
	{
		ID:             "google-analytics-admin-properties.custom-metrics.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customMetrics",
		Summary:        "Lists CustomMetrics on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists CustomMetrics on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/customMetrics"),
	},
	{
		ID:             "google-analytics-admin-properties.data-streams.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/dataStreams",
		Summary:        "Creates a DataStream.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a DataStream.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/dataStreams"),
	},
	{
		ID:             "google-analytics-admin-properties.data-streams.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/dataStreams",
		Summary:        "Lists DataStreams on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists DataStreams on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/dataStreams"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-link-proposals.approve",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}:approve",
		Summary:        "Approves a DisplayVideo360AdvertiserLinkProposal.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "approve", "Approves a DisplayVideo360AdvertiserLinkProposal.", "https://analyticsadmin.googleapis.com/v1alpha/{name}:approve"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-link-proposals.cancel",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}:cancel",
		Summary:        "Cancels a DisplayVideo360AdvertiserLinkProposal.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "cancel", "Cancels a DisplayVideo360AdvertiserLinkProposal.", "https://analyticsadmin.googleapis.com/v1alpha/{name}:cancel"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-link-proposals.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinkProposals",
		Summary:        "Creates a DisplayVideo360AdvertiserLinkProposal.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a DisplayVideo360AdvertiserLinkProposal.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinkProposals"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-link-proposals.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinkProposals",
		Summary:        "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists DisplayVideo360AdvertiserLinkProposals on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinkProposals"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-links.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinks",
		Summary:        "Creates a DisplayVideo360AdvertiserLink.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a DisplayVideo360AdvertiserLink.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.display-video360-advertiser-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinks",
		Summary:        "Lists all DisplayVideo360AdvertiserLinks on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists all DisplayVideo360AdvertiserLinks on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/displayVideo360AdvertiserLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.expanded-data-sets.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/expandedDataSets",
		Summary:        "Creates a ExpandedDataSet.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a ExpandedDataSet.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/expandedDataSets"),
	},
	{
		ID:             "google-analytics-admin-properties.expanded-data-sets.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/expandedDataSets",
		Summary:        "Lists ExpandedDataSets on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists ExpandedDataSets on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/expandedDataSets"),
	},
	{
		ID:             "google-analytics-admin-properties.firebase-links.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/firebaseLinks",
		Summary:        "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a FirebaseLink. Properties can have at most one FirebaseLink.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/firebaseLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.firebase-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/firebaseLinks",
		Summary:        "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/firebaseLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.google-ads-links.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/googleAdsLinks",
		Summary:        "Creates a GoogleAdsLink.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a GoogleAdsLink.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/googleAdsLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.google-ads-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/googleAdsLinks",
		Summary:        "Lists GoogleAdsLinks on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists GoogleAdsLinks on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/googleAdsLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.search-ads360-links.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/searchAds360Links",
		Summary:        "Creates a SearchAds360Link.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a SearchAds360Link.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/searchAds360Links"),
	},
	{
		ID:             "google-analytics-admin-properties.search-ads360-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/searchAds360Links",
		Summary:        "Lists all SearchAds360Links on a property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists all SearchAds360Links on a property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/searchAds360Links"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.audit",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:audit",
		Summary:        "Lists all user links on an account or property",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "audit", "Lists all user links on an account or property", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:audit"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.batch-create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchCreate",
		Summary:        "Creates information about multiple users' links to an account or property. This method is transactional.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-create", "Creates information about multiple users' links to an account or property. This method is transactional.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchCreate"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.batch-delete",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchDelete",
		Summary:        "Deletes information about multiple users' links to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-delete", "Deletes information about multiple users' links to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchDelete"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.batch-get",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchGet",
		Summary:        "Gets information about multiple users' links to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "names", WireName: "names", QueryArray: true, QueryStyle: "form", QueryExplode: true}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-get", "Gets information about multiple users' links to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchGet"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.batch-update",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchUpdate",
		Summary:        "Updates information about multiple users' links to an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "batch-update", "Updates information about multiple users' links to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks:batchUpdate"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.create",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks",
		Summary:        "Creates a user link on an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "notifyNewUser", WireName: "notifyNewUser"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "create", "Creates a user link on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.delete",
		Method:         "DELETE",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}",
		Summary:        "Deletes a user link on an account or property.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "delete", "Deletes a user link on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{name}"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.get",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}",
		Summary:        "Gets information about a user's link to an account or property.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "get", "Gets information about a user's link to an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{name}"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.list",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks",
		Summary:        "Lists all user links on an account or property.",
		Positional:     []string{"parent"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "pageSize", WireName: "pageSize"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "list", "Lists all user links on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{parent}/userLinks"),
	},
	{
		ID:             "google-analytics-admin-properties.user-links.patch",
		Method:         "PATCH",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/{name}",
		Summary:        "Updates a user link on an account or property.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "updateMask", WireName: "updateMask"}},
		keywords:       codeOrchKeywords("google-analytics-admin-properties", "patch", "Updates a user link on an account or property.", "https://analyticsadmin.googleapis.com/v1alpha/{name}"),
	},
	{
		ID:             "properties.batch-run-pivot-reports",
		Method:         "POST",
		Path:           "/v1beta/{property}:batchRunPivotReports",
		Summary:        "Returns multiple pivot reports in a batch. All reports must be for the same GA4 Property.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "batch-run-pivot-reports", "Returns multiple pivot reports in a batch. All reports must be for the same GA4 Property.", "/v1beta/{property}:batchRunPivotReports"),
	},
	{
		ID:             "properties.batch-run-reports",
		Method:         "POST",
		Path:           "/v1beta/{property}:batchRunReports",
		Summary:        "Returns multiple reports in a batch. All reports must be for the same GA4 Property.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "batch-run-reports", "Returns multiple reports in a batch. All reports must be for the same GA4 Property.", "/v1beta/{property}:batchRunReports"),
	},
	{
		ID:             "properties.check-compatibility",
		Method:         "POST",
		Path:           "/v1beta/{property}:checkCompatibility",
		Summary:        "This compatibility method lists dimensions and metrics that can be added to a report request and maintain compatibility.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "check-compatibility", "This compatibility method lists dimensions and metrics that can be added to a report request and maintain compatibility.", "/v1beta/{property}:checkCompatibility"),
	},
	{
		ID:             "properties.get-metadata",
		Method:         "GET",
		Path:           "/v1beta/{name}",
		Summary:        "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics.",
		Positional:     []string{"name"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "get-metadata", "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics.", "/v1beta/{name}"),
	},
	{
		ID:             "properties.run-pivot-report",
		Method:         "POST",
		Path:           "/v1beta/{property}:runPivotReport",
		Summary:        "Returns a customized pivot report of your Google Analytics event data.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "run-pivot-report", "Returns a customized pivot report of your Google Analytics event data.", "/v1beta/{property}:runPivotReport"),
	},
	{
		ID:             "properties.run-realtime-report",
		Method:         "POST",
		Path:           "/v1beta/{property}:runRealtimeReport",
		Summary:        "Returns a customized report of realtime event data for your property.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "run-realtime-report", "Returns a customized report of realtime event data for your property.", "/v1beta/{property}:runRealtimeReport"),
	},
	{
		ID:             "properties.run-report",
		Method:         "POST",
		Path:           "/v1beta/{property}:runReport",
		Summary:        "Returns a customized report of your Google Analytics event data.",
		Positional:     []string{"property"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties", "run-report", "Returns a customized report of your Google Analytics event data.", "/v1beta/{property}:runReport"),
	},
	{
		ID:             "properties-create-connected-site-tag.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:createConnectedSiteTag",
		Summary:        "Creates a connected site tag for a Universal Analytics property.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties-create-connected-site-tag", "analyticsadmin", "Creates a connected site tag for a Universal Analytics property.", "https://analyticsadmin.googleapis.com/v1alpha/properties:createConnectedSiteTag"),
	},
	{
		ID:             "properties-delete-connected-site-tag.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:deleteConnectedSiteTag",
		Summary:        "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties-delete-connected-site-tag", "analyticsadmin", "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.", "https://analyticsadmin.googleapis.com/v1alpha/properties:deleteConnectedSiteTag"),
	},
	{
		ID:             "properties-fetch-automated-ga4-configuration-opt-out.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
		Summary:        "Fetches the opt out status for the automated GA4 setup process for a UA property.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties-fetch-automated-ga4-configuration-opt-out", "analyticsadmin", "Fetches the opt out status for the automated GA4 setup process for a UA property.", "https://analyticsadmin.googleapis.com/v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut"),
	},
	{
		ID:             "properties-fetch-connected-ga4-property.analyticsadmin",
		Method:         "GET",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:fetchConnectedGa4Property",
		Summary:        "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "property", WireName: "property"}},
		keywords:       codeOrchKeywords("properties-fetch-connected-ga4-property", "analyticsadmin", "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.", "https://analyticsadmin.googleapis.com/v1alpha/properties:fetchConnectedGa4Property"),
	},
	{
		ID:             "properties-list-connected-site-tags.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:listConnectedSiteTags",
		Summary:        "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties-list-connected-site-tags", "analyticsadmin", "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned.", "https://analyticsadmin.googleapis.com/v1alpha/properties:listConnectedSiteTags"),
	},
	{
		ID:             "properties-set-automated-ga4-configuration-opt-out.analyticsadmin",
		Method:         "POST",
		Path:           "https://analyticsadmin.googleapis.com/v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
		Summary:        "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("properties-set-automated-ga4-configuration-opt-out", "analyticsadmin", "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.", "https://analyticsadmin.googleapis.com/v1alpha/properties:setAutomatedGa4ConfigurationOptOut"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	text, err := bound.JSON(map[string]any{"count": len(out), "results": out})
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call google-analytics_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call google-analytics_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		path = codeOrchSplitQuery(path, ep.QueryParams, params)
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		path = codeOrchSplitQuery(path, ep.QueryParams, params)
	}

	hdrs := ep.HeaderOverrides
	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			data, err = c.GetWithHeaders(ctx, path, query, hdrs)
		} else {
			data, err = c.Get(ctx, path, query)
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(bound.EndpointResponse(ep.Method, data)), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// appends them URL-encoded to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(path string, queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				if q.QueryArray {
					path = appendMCPArrayQueryParam(path, q.WireName, v, q.QueryStyle, q.QueryExplode)
				} else {
					uv.Set(q.WireName, formatMCPParamValue(v))
				}
				delete(params, key)
				break
			}
		}
	}
	if enc := uv.Encode(); enc != "" {
		sep := "?"
		if strings.Contains(path, "?") {
			sep = "&"
		}
		path += sep + enc
	}
	return path
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
